### ISSUE TITLE
WMS/GetCapabilities unfinished with layers using CLASSGROUP

### ISSUE THREAD

**Issue by elzouavo** [mapserver/mapserver#4571] opened 2013-01-23 16:18 UTC
I have compiled MapServer 6.2.0 on Debian 6.0.4 to replace the 6.1 dev future 6.2 rev13312.
I note a regression with WMS/GetCapabilities (1.1.1 and 1.3.0) with layers using CLASSGROUP. The XML is interrupted. I've turned debug to 5 but nothing appears in log file!
If I remove CLASSGROUP all works fine. This mapfile was OK in 6.1dev rev13312.

I will attach some files if necessary to help you.

**Comment by jratike80** [comment] 2015-11-02 10:54
Without a mapfile this issue can never be resolved. It can't be that CLASSGROUP is generally breaking GetCapabilities but it must be something special in your mapfile or environment. I do not mean that the issue is not real.

**Comment by elzouavo** [comment] 2015-11-02 14:01
Here is the layer that causes this issue :
https://gist.github.com/anonymous/856a229c9b0167313a87

**Comment by jratike80** [comment] 2015-11-10 15:25
I added your layer into my existing mapfile and WMS 1.3.0 GetCapabilities. I had to comment out the PostGIS connection line "#INCLUDE     		"/opt/data/carto/ref/ms/conf/mnt_2012.conf" # Access to PostGIS database" but anyway, the mapfile is parsed without errors.

**Comment by jratike80** [comment] 2017-08-25 12:38
No reaction from the author, verified to work for another user, closing.

**Closed by jratike80** 2017-08-25 12:38 UTC
Labels: Bug, WMS Server
