### ISSUE TITLE
CONTOUR from GFS GRIB file broken

### ISSUE THREAD

**Issue by sgofferj** [MapServer/MapServer#6261] opened 2021-03-13 11:45 UTC
## Expected behavior and actual behavior.
I am trying to create contour maptiles from a NOAA GFS GRIB file, specifically the pressure MSL forecast. The result does not look as it should:
![Screenshot_20210313_132105](https://user-images.githubusercontent.com/3258466/111028497-ac90c500-83ff-11eb-8cc0-81aa392007d0.png)

The NOAA files have their longitude from 0 to 360 instead of -180 to 180. I account for that with the following projection:
```
    PROJECTION
      "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs +lon_wrap=180"
    END
```
That works fine for raster outputs.

## Steps to reproduce the problem.
Get a GFS GRIB file from NOMADS and try to render contours from it.

## Attach simple test case (drag/drop it here)
The GFS data files are enourmous, so I'd rather not upload any here. Any GFS GRIB file from NOMADS can be used.
Example: https://nomads.ncep.noaa.gov/pub/data/nccf/com/gfs/prod/gfs.20210313/06/gfs.t06z.pgrb2.0p25.f000

This is my config:
```
MAP
  PROJECTION
    "init=epsg:3857"
  END

  NAME "WMS_server"
  STATUS ON
  SIZE 400 300
  EXTENT -180 -90 180 90
  UNITS DD
  IMAGECOLOR 255 255 255

  IMAGETYPE PNG24

  OUTPUTFORMAT
        NAME png
        DRIVER "GD/PNG"
        MIMETYPE "image/png"
        IMAGEMODE PC256
        EXTENSION "png"
  END
  OUTPUTFORMAT
        NAME png24
        DRIVER "GD/PNG"
        MIMETYPE "image/png"
        IMAGEMODE RGBA
        EXTENSION "png"
  END
  OUTPUTFORMAT
        NAME jpeg
        DRIVER "GD/JPEG"
        FORMATOPTION "QUALITY=75"
        MIMETYPE "image/jpeg"
        IMAGEMODE RGB
        EXTENSION "jpg"
  END
 
  WEB
    IMAGEPATH "/ms4w/tmp/ms_tmp/"
    IMAGEURL "/ms_tmp/"
    METADATA
      "wms_onlineresource" "http://nostromo:8085/cgi-bin/?"
      "wms_title"          "WMS Demo Server for MapServer"
      "wms_srs"            "EPSG:3857" ## Recommended
      "wms_abstract"       "This text describes my WMS service."
      "wms_enable_request" "*"  # necessary
    END
  END

  LAYER
    NAME "Testlayer"
    PROJECTION
      "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs +lon_wrap=180"
    END
    METADATA
      "wms_title"          "Testlayer"
      "wms_srs"            "EPSG:3857"
    END
    STATUS ON
    TYPE LINE
    CONNECTIONTYPE CONTOUR
    DATA "/mapdata/prmsl.grib"
    PROCESSING "BANDS=2"
    PROCESSING "CONTOUR_INTERVAL=0,5000000:100"
    PROCESSING "CONTOUR_INTERVAL=5000000,0:500"
    CLASS
      STYLE
        BACKGROUNDCOLOR "#ffffff00"
        COLOR 255 0 0
      END
    END
  END
END
```

## Operating system
Ubuntu 16.04 64 bit

## MapServer version and installation method
`MapServer version 7.6.2 OUTPUT=PNG OUTPUT=JPEG OUTPUT=KML SUPPORTS=PROJ SUPPORTS=AGG SUPPORTS=FREETYPE SUPPORTS=CAIRO SUPPORTS=SVG_SYMBOLS SUPPORTS=RSVG SUPPORTS=ICONV SUPPORTS=FRIBIDI SUPPORTS=WMS_SERVER SUPPORTS=WMS_CLIENT SUPPORTS=WFS_SERVER SUPPORTS=WFS_CLIENT SUPPORTS=WCS_SERVER SUPPORTS=SOS_SERVER SUPPORTS=FASTCGI SUPPORTS=GEOS SUPPORTS=POINT_Z_M SUPPORTS=PBF INPUT=JPEG INPUT=POSTGIS INPUT=OGR INPUT=GDAL INPUT=SHAPEFILE
`

Docker: camptocamp/mapserver:7.6

**Comment by sgofferj** [comment] 2021-03-14 10:16
I actually had a similar issue when I wrote my current map processing scripts. Issue was that I did the contour creation first and then reprojected the result. After switching the sequence, it worked fine.

**Comment by sgofferj** [comment] 2021-03-15 17:04
Possibly related to #6106?

**Comment by jmckenna** [comment] 2021-03-20 17:53
@sgofferj As the instructions in the ticket template mentioned here, please take the time to create a .zip with your sample files (data, mapfile, commands.txt).  Those GRIB files can still be zipped and uploaded to a free file sharing service, and you could paste the link.  You pointed to the one file, but there is a .idx file also to include, be sure to include all associated files.  Also in your commands.txt, outline what the source projection is (your mapfile oddly outputs to 3857 but has a source extent in 4326 & DD units, which will cause problems for sure downstream).  Since you are the reporter and familiar with this data (it's not my job to learn your data, we are not on a paid project together) please dig into the source data metadata/data schema for Nomad GFS and outline the source projection, or point to that metadata in your commands.txt   Bonus points if your commands.txt contains the exact 'shp2img' command to reproduce your problem map image.

Finally, please always start by asking the MapServer community directly, direct to the MapServer users, who are waiting to help you, by sending your question to the 'mapserver-users' list (there are thousands of eyes waiting to read your message there).  You can there paste the zip link to your packaged test, and ask the users to try your steps to reproduce (remember, the easier you make it for someone to run your mapfile, the more chances you will get someone to take hours of their free time to run your tests and give feedback).  Subscribe at https://lists.osgeo.org/listinfo/mapserver-users

I will close this ticket now, but, could the 'mapserver-users' feedback on that list cause you to confirm that this is in fact a bug, please come back here and re-open ticket.

**Closed by jmckenna** 2021-03-20 17:53 UTC

**Comment by sgofferj** [comment] 2021-03-20 18:56
@jmckenna Ok, I'll post to the list. The IDX file is not relevant. It contains a list of byte ranges for single parameters, so you can download only the parts of the grib file you need.
Where do I find that commands.txt?

**Comment by jmckenna** [comment] 2021-03-20 19:01
@sgofferj 'commands.txt' is made by you, containing all the commands (shp2img or mapserv) and steps to reproduce.  thanks.
