### ISSUE TITLE
RFC 118 & Geotransform

### ISSUE THREAD

**Issue by pelord** [mapserver/mapserver#5744] opened 2019-02-18 16:29 UTC
Here my class for a linestring stored in postgis as a multilinestring.

```
CLASSITEM "state"
CLASS
	NAME "bad"
	EXPRESSION 'bad'
	STYLE
		LINECAP butt
		WIDTH 8
		COLOR 255 165 0
	END
	STYLE
		GEOMTRANSFORM "end"
		SYMBOL "vertline"
		COLOR 0 0 0
		SIZE 13
		WIDTH 1
		ANGLE AUTO
	END
	STYLE
		GEOMTRANSFORM "start"
		SYMBOL "vertline"
		COLOR 0 0 0
		SIZE 13
		WIDTH 1
		ANGLE AUTO
	END
END
CLASS
...
END 
```

If I don't apply a wms filter, everything is rendered (getmap) as in the class's definition. 
![image](https://user-images.githubusercontent.com/7397743/52964145-a1c5ec00-336f-11e9-9756-cb843e9aec85.png)

If a apply a filter (rfc 118):

`<Filter xmlns="http://www.opengis.net/ogc"><PropertyIsEqualTo matchCase="true"><PropertyName>state</PropertyName><Literal>bad</Literal></PropertyIsEqualTo>
`
Here the result.

![image](https://user-images.githubusercontent.com/7397743/52964183-b7d3ac80-336f-11e9-974f-109c41a5f1cd.png)

A query on wms with geotransform end/start seem to render a densified version of the linestring. 

Here  the vertices of this line:
![image](https://user-images.githubusercontent.com/7397743/52964104-83f88700-336f-11e9-8c08-d12d6d8cedae.png)

I've tried to convert the multilinestring to a linestring  as done on [gis.stackexchange](https://gis.stackexchange.com/questions/19864/converting-multilinestring-to-linestring-with-postgis) with the same result.

Is it an issue or a bad mapfile definition?

 MapServer version 7.2.1

**Comment by pelord** [comment] 2019-02-18 16:39
The same result with GEOMTRANSFORM "vertices".

**Comment by sdlime** [comment] 2019-03-12 20:41
I think it's a bug, likely in the query map code. What happens if you add:

    QUERYMAP
      STYLE NORMAL
    END

to your mapfile?

**Comment by pelord** [comment] 2019-03-13 14:12
Same result.

**Comment by sdlime** [comment] 2019-03-13 14:51
Then it's a problem in the msDrawQuery() function in mapdraw.c not properly handling GEOMTRANSFORMs... nuts. Dan alluded to other issues in the limitations section of the RFC and I guess this is another one. I'm curious if POLYGONs behave the same. The function in question uses msDrawShape() for polygons but calls lower-level functions for lines.

**Comment by pelord** [comment] 2019-03-13 15:20
Polygons do not have the same behavior (geotransform "start")

Without filter:
![image](https://user-images.githubusercontent.com/7397743/54290769-f3822080-4581-11e9-96bd-956a30c5a1ba.png)

With filter:
![image](https://user-images.githubusercontent.com/7397743/54290803-ff6de280-4581-11e9-9a66-cc68128ac536.png)

**Comment by sdlime** [comment] 2019-03-13 15:49
That's what I was hoping would happen - it's a good hint.. The question is if msDrawShape() can also be used for line features in msDrawQuery().

**Comment by pelord** [comment] 2019-03-13 15:51
I can't answer to this question :)

**Comment by sdlime** [comment] 2019-03-16 14:51
@pelord, what does your vertline symbol definition look like?

**Comment by pelord** [comment] 2019-03-16 19:48
```
	SYMBOL
		NAME "vertline"
		TYPE vector
		FILLED true
		POINTS
			0 0
			0 5
			1 5
			1 0
			0 0
		END
	END
```

**Comment by pelord** [comment] 2019-07-31 23:21
@geographika  Do you think this could be related to your issue? 

http://osgeo-org.1560.x6.nabble.com/Combining-WMS-Filter-and-Style-Parameters-td5411882.html

**Comment by geographika** [comment] 2019-08-01 13:00
@pelord - yes it looks like it is the same issue, although I'm not using `GEOTRANSFORM` - just filters and styles on a WMS. 
I've made a simple test case to demonstrate the issue (tested on MapServer 7.4.1 on Windows). 

The example uses [test_wms_filter.map.txt](https://github.com/mapserver/mapserver/files/3456791/test_wms_filter.map.txt) (remove the `.txt` extension required to upload to GitHub).

A basic WMS request with the `&STYLES=green` style selected:

```
mapserv -nh "QUERY_STRING=map=test_wms_filter.map&layers=INLINE&SERVICE=WMS&REQUEST=GetMap&VERSION=1.3.0&STYLES=green&FORMAT=image/png&TRANSPARENT=true&HEIGHT=256&WIDTH=256&CRS=epsg:4326&BBOX=-10,-10,10,10" > test_green.png
```

Works fine:

![test_green](https://user-images.githubusercontent.com/490840/62294861-2d3dc000-b46c-11e9-891f-a0ce0b800434.png)

A basic WMS request with the `&STYLES=red`:

```
mapserv -nh "QUERY_STRING=map=test_wms_filter.map&layers=INLINE&SERVICE=WMS&REQUEST=GetMap&VERSION=1.3.0&STYLES=red&FORMAT=image/png&TRANSPARENT=true&HEIGHT=256&WIDTH=256&CRS=epsg:4326&BBOX=-10,-10,10,10" > test_red.png
```
![test_red](https://user-images.githubusercontent.com/490840/62294909-4a728e80-b46c-11e9-8f85-d13ae9ac4bc7.png)

The failing case is below - `&STYLES=red` but with a `&filter=<Filter</Filter>` clause. Records are filterered correctly but displayed in green. It seems that whatever is set in `CLASSGROUP` is used for the style not the one passed in by the WMS. If `CLASSGROUP` is removed then it displays whichever `CLASS` is first for the layer. 

```
mapserv -nh "QUERY_STRING=map=test_wms_filter.map&layers=INLINE&SERVICE=WMS&REQUEST=GetMap&VERSION=1.3.0&STYLES=red&FORMAT=image/png&TRANSPARENT=true&HEIGHT=256&WIDTH=256&CRS=epsg:4326&BBOX=-10,-10,10,10&filter=<Filter><PropertyIsEqualTo><PropertyName>property1</PropertyName><Literal>value1</Literal></PropertyIsEqualTo></Filter>" > test_with_filter.png
```

![test_with_filter](https://user-images.githubusercontent.com/490840/62294867-3169dd80-b46c-11e9-91b8-34e1588bc18d.png)

**Comment by pelord** [comment] 2019-08-01 19:02
Let me know if I could help!

**Comment by geographika** [comment] 2019-08-02 07:51
I've done some debugging, and I think I know why this is happening, but not much idea how to fix it. 

I believe it is the same issue as referenced in the [RFC](https://mapserver.org/development/rfc/ms-rfc-118.html):

`
Since rendering of the filtered layers is done via the QUERYMAP mechanism, the MASK, OPACITY and COMPOSITE settings are ignored since they are not implemented for QUERYMAPs. (This could be considered a QUERYMAP bug but is out of scope for this RFC)
`

I believe this is a similar case for `CLASSGROUP` (and possibly `GEOTRANSFORM`). 

A layer with a filter uses `msDrawQueryLayer` rather than the standard `msDrawLayer` - decided in [mapdraw.c](https://github.com/mapserver/mapserver/blob/d2e05178ae54165481c47f2adc93c619c901bdae/mapdraw.c#L394)

There is a [comment](https://github.com/mapserver/mapserver/blob/d2e05178ae54165481c47f2adc93c619c901bdae/mapdraw.c#L1402) in `msDrawQueryLayer`:

`  ** Layer was opened as part of the query process, msLayerWhichItems() has also been run, shapes have been classified - start processing!`

`msLayerWhichItems` is called earlier - but the classgroup is set to 0 at this stage, so `layer->resultcache` may not have taken into account the `CLASSGROUP` set by the style?

**Comment by sdlime** [comment] 2019-08-02 12:17
I know where in the code the problem lies. What’s not clear is how to fix it. The query layer rendering probably needs to be refactored so that it uses the regular pipeline as much as possible. This isn’t specific to WMS. Straight MapServer queries with an image qformat also demonstrate the issue.
________________________________

**Comment by geographika** [comment] 2019-08-03 08:32
@sdlime - I'd already done some tests and debugging before @pelord pointed me to this issue so thought I'd add them in. Let me know if you need any testing done or test cases. The refactoring of `msDrawLayer` and `msDrawQueryLayer` looks challenging.

**Comment by geographika** [comment] 2019-08-21 08:53
A minor update, I tried setting `querymap` to 0 [here](https://github.com/mapserver/mapserver/blob/d2e05178ae54165481c47f2adc93c619c901bdae/mapdraw.c#L220) to force the "regular drawing pipeline". In the test case with the red and green points then nothing is displayed with msDrawLayer when using a filter. Not sure if that provides anything useful.

**Comment by sdlime** [comment] 2019-11-12 19:38
Can you guys give the pull request a test? There are likely still issues with HILITE querymap styles and knowing which styles to change colors on in certain cases. This should address cases where a style sets an outline width and uses GEOMTRANSFORM at the style level.

**Comment by pelord** [comment] 2019-11-12 19:42
Sorry, I do not have the experience/environnement for compiling Mapserver and test it. I'll try soon to do it but it might be extremely time consuming for me.

**Comment by geographika** [comment] 2019-11-13 09:47
@sdlime - I've compiled the code from the [issue-5744](https://github.com/sdlime/mapserver/tree/issue-5744) branch (just for info this is about 6 months of commits behind master). 

Unfortunately I still have the same issue where applying a filter reverts to using the first style - [the third test here](https://github.com/mapserver/mapserver/issues/5744#issuecomment-517277267).

**Comment by sdlime** [comment] 2019-11-13 17:35
Anyway to create a succinct version of the 3rd test?

**Comment by geographika** [comment] 2019-11-13 20:07
@sdlime - I can add as an msautotest to your branch?

**Comment by sdlime** [comment] 2019-11-15 18:29
No, that's ok, I now see the mapfile and sample calls above and can work with that. I don't think this is the same issue. @pelord's problems were specific to lines and the msDrawQueryLayer() code was clearly not following the same approach as msDrawVectorLayer() in terms of dealing with outlinewidth, GEOMTRANFORMed styles, etc... That's what the pull request fixes.

Your issue is with point layers which would have been drawn correctly as the code sits now. The msDrawQueryLayer() code doesn't assign a class index to a selected feature. That's done upstream in the query code (since that's where template references could possibly live). The drawing code just leverages the set class index and then tweaks colors if necessary (TYPE HILITE). Seems to me like the class index isn't being set properly elsewhere. That will be easy to verify. I know the main query functions respect the CLASSGROUP but I don't know what the WMS code is doing.

**Comment by sdlime** [comment] 2019-11-15 21:08
I can confirm that the class index in the 3rd case is reported as 0, so CLASSGROUP "green". The problem is elsewhere in the query code I think.

**Comment by sdlime** [comment] 2019-11-15 21:57
@dmorissette, you're way more familiar with the WMS code than I am - only the previous comment is really relevant. Does the issue of setting a layers class group after doing a query seem like something that could be happening?

**Comment by sdlime** [comment] 2019-12-28 17:39
This has been fixed in both master and branch-7-4. Closing... --Steve

**Closed by sdlime** 2019-12-28 17:39 UTC

**Comment by pelord** [comment] 2021-04-27 00:47
I am currently testing version 7.6.2 and I confirm that this problem is fixed. Sorry for the delay!

**Comment by sdlime** [comment] 2021-04-27 14:31
Thanks @pelord!
