### ISSUE TITLE
data loss on getmap requests when vector data is reprojected EPSG:2056 to EPSG:4326

### ISSUE THREAD

**Issue by ltclm** [MapServer/MapServer#7019] opened 2024-01-25 14:41 UTC
## Expected behavior and actual behavior.

When zooming into a reprojected polygon layer we expect that all the features are displayed in all scales. The original data and the mapfile configuration is in EPSG:2056. The strange behaviour and the data loss has been observed when requesting the map in EPSG:4326.

## Steps to reproduce the problem.
Using the mapfile config [1] and the data index.shp from the attachment [2],  start zooming into the center of the 4 polygons in EPSG:4326. After a certain zoom/scale some data gets lost. The same effect occurs with tiled wms queries (256x256), but much earlier.

## Attach simple test case (drag/drop it here)
here are some screenshots and getmap requests of the observed data loss with EPSG:4326 GetMap Requests:
http://localhost:9178/local/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=47.70122100713624036,8.631010777621343166,47.73459661396240961,8.673423389810198003&CRS=EPSG:4326&WIDTH=1591&HEIGHT=1252&LAYERS=test&STYLES=&FORMAT=image/jpeg&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96
![image](https://github.com/MapServer/MapServer/assets/5286659/ee7b6b65-1b2c-4e0f-b65b-4cefbff32d35)
```
service-wms_1  |  [warn] [pid 10016] mod_fcgid: stderr: CGI Request 4 on process 10071
service-wms_1  |  [warn] [pid 10016] mod_fcgid: stderr: msDrawMap(): rendering using outputformat named jpeg (AGG/JPEG).
service-wms_1  |  [warn] [pid 10016] mod_fcgid: stderr: msDrawMap(): WMS/WFS set-up and query, 0.000s
service-wms_1  |  [warn] [pid 10016] mod_fcgid: stderr: msDrawMap(): Layer 0 (test), 0.016s
service-wms_1  |  [warn] [pid 10016] mod_fcgid: stderr: msDrawMap(): Drawing Label Cache, 0.000s
service-wms_1  |  [warn] [pid 10016] mod_fcgid: stderr: msDrawMap() total time: 0.017s
service-wms_1  |  [warn] [pid 10016] mod_fcgid: stderr: msSaveImage(stdout) total time: 0.014s
service-wms_1  |  [warn] [pid 10016] mod_fcgid: stderr: mapserv request processing time (msLoadMap not incl.): 0.031s
service-wms_1  |  [warn] [pid 10016] mod_fcgid: stderr: msFreeMap(): freeing map at 0x562ec0ee5e50.
service-wms_1  | 172.24.0.1 - - [26/Jan/2024:07:23:39 +0000] "GET /local/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=47.70122100713624036,8.631010777621343166,47.73459661396240961,8.673423389810198003&CRS=EPSG:4326&WIDTH=1591&HEIGHT=1252&LAYERS=test&STYLES=&FORMAT=image/jpeg&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96 HTTP/1.1" 200 25612
```

http://localhost:9178/local/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=47.70991146067085253,8.640854182430102171,47.72659926408394426,8.662060488524529589&CRS=EPSG:4326&WIDTH=1591&HEIGHT=1253&LAYERS=test&STYLES=&FORMAT=image/jpeg&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96
![image](https://github.com/MapServer/MapServer/assets/5286659/0ae7cde6-4a00-47a2-a57c-a8d2cdffafe0)
```
service-wms_1  |  [warn] [pid 10016] mod_fcgid: stderr: CGI Request 5 on process 10071
service-wms_1  |  [warn] [pid 10016] mod_fcgid: stderr: msDrawMap(): rendering using outputformat named jpeg (AGG/JPEG).
service-wms_1  |  [warn] [pid 10016] mod_fcgid: stderr: msDrawMap(): WMS/WFS set-up and query, 0.000s
service-wms_1  |  [warn] [pid 10016] mod_fcgid: stderr: msDrawMap(): Layer 0 (test), 0.038s
service-wms_1  |  [warn] [pid 10016] mod_fcgid: stderr: msDrawMap(): Drawing Label Cache, 0.000s
service-wms_1  |  [warn] [pid 10016] mod_fcgid: stderr: msDrawMap() total time: 0.039s
service-wms_1  |  [warn] [pid 10016] mod_fcgid: stderr: msSaveImage(stdout) total time: 0.021s
service-wms_1  |  [warn] [pid 10016] mod_fcgid: stderr: mapserv request processing time (msLoadMap not incl.): 0.061s
service-wms_1  |  [warn] [pid 10016] mod_fcgid: stderr: msFreeMap(): freeing map at 0x562ec0ee5e50.
service-wms_1  | 172.24.0.1 - - [26/Jan/2024:07:25:10 +0000] "GET /local/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=47.70991146067085253,8.640854182430102171,47.72659926408394426,8.662060488524529589&CRS=EPSG:4326&WIDTH=1591&HEIGHT=1253&LAYERS=test&STYLES=&FORMAT=image/jpeg&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96 HTTP/1.1" 200 19836
```

http://localhost:9178/local/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=47.7172290358096447,8.65006363064953554,47.71931501123628294,8.652714418911338967&CRS=EPSG:4326&WIDTH=1591&HEIGHT=1253&LAYERS=test&STYLES=&FORMAT=image/jpeg&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96
![image](https://github.com/MapServer/MapServer/assets/5286659/f815f789-9937-43e7-a0f1-1bdb32714019)
```
service-wms_1  |  [warn] [pid 10015] mod_fcgid: stderr: CGI Request 6 on process 10071
service-wms_1  |  [warn] [pid 10015] mod_fcgid: stderr: msDrawMap(): rendering using outputformat named jpeg (AGG/JPEG).
service-wms_1  |  [warn] [pid 10015] mod_fcgid: stderr: msDrawMap(): WMS/WFS set-up and query, 0.000s
service-wms_1  |  [warn] [pid 10015] mod_fcgid: stderr: msDrawMap(): Layer 0 (test), 0.020s
service-wms_1  |  [warn] [pid 10015] mod_fcgid: stderr: msDrawMap(): Drawing Label Cache, 0.000s
service-wms_1  |  [warn] [pid 10015] mod_fcgid: stderr: msDrawMap() total time: 0.021s
service-wms_1  |  [warn] [pid 10015] mod_fcgid: stderr: msSaveImage(stdout) total time: 0.018s
service-wms_1  |  [warn] [pid 10015] mod_fcgid: stderr: mapserv request processing time (msLoadMap not incl.): 0.039s
service-wms_1  |  [warn] [pid 10015] mod_fcgid: stderr: msFreeMap(): freeing map at 0x562ec0ee5e50.
service-wms_1  | 172.24.0.1 - - [26/Jan/2024:07:25:52 +0000] "GET /local/?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=47.7172290358096447,8.65006363064953554,47.71931501123628294,8.652714418911338967&CRS=EPSG:4326&WIDTH=1591&HEIGHT=1253&LAYERS=test&STYLES=&FORMAT=image/jpeg&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96 HTTP/1.1" 200 18001
```

## Operating system
We are operating mapserver on aws/kubernetes using this docker image from dockerhub:  `camptocamp/mapserver:7.6-gdal3.3`. The docker image is based on `Ubuntu 20.04.6 LTS`

## MapServer version and installation method
```
mapserv -v
MapServer version 7.6.5 OUTPUT=PNG OUTPUT=JPEG OUTPUT=KML SUPPORTS=PROJ SUPPORTS=AGG SUPPORTS=FREETYPE SUPPORTS=CAIRO SUPPORTS=SVG_SYMBOLS SUPPORTS=RSVG SUPPORTS=ICONV SUPPORTS=FRIBIDI SUPPORTS=WMS_SERVER SUPPORTS=WMS_CLIENT SUPPORTS=WFS_SERVER SUPPORTS=WFS_CLIENT SUPPORTS=WCS_SERVER SUPPORTS=SOS_SERVER SUPPORTS=FASTCGI SUPPORTS=GEOS SUPPORTS=POINT_Z_M SUPPORTS=PBF INPUT=JPEG INPUT=POSTGIS INPUT=OGR INPUT=GDAL INPUT=SHAPEFILE
root@1b9c4dc20d26:/# proj --version
Rel. 8.2.0, November 1st, 2021
root@1b9c4dc20d26:/# gdal_translate --version
GDAL 3.3.3, released 2021/10/25
```

the same behaviour has been observed with `mapserver 8.0 / gdal 3.6` and `mapserver 8.0 / gdal 3.8`
[1] mapfile
```
MAP
  NAME "WMS-BGDI"

  EXTENT 2100000 1030000 2900000 1400000
  SHAPEPATH "/var/local/geodata"

  PROJECTION
    "init=epsg:2056"
  END

  WEB
    METADATA
      "wms_title"   "WMS-BGDI"
      "wms_srs"     "EPSG:2056 EPSG:21781 EPSG:4326 EPSG:31466 EPSG:31467 EPSG:31468 EPSG:25832 EPSG:27582 EPSG:26591 EPSG:26592 EPSG:900913"
      "wms_extent"  "2100000 1030000 2900000 1400000"
    END
  END

  CONFIG "MS_ERRORFILE" stderr
  CONFIG "CPL_DEBUG" "ON"
  CONFIG "CPL_CURL_VERBOSE" "ON"
  CONFIG "CPL_TIMESTAMP" "ON"
  CONFIG "PROJ_DEBUG" "ON"
  DEBUG 5

  LAYER
    NAME "test"
    TYPE POLYGON
    STATUS ON
    DATA bund/swisstopo/swissimage/test/index.shp
    COMPOSITE
        OPACITY 40
    END
    METADATA
        "wms_enable_request" "*"
        "wms_extent"  "2100000 1030000 2900000 1400000"
    END
    CLASS
      STYLE
        OUTLINECOLOR 255 0 0
        COLOR 255 255 0
        WIDTH 5
      END
    END
    PROJECTION
        "init=epsg:2056"
    END
  END
END
```
[2]
[data.zip](https://github.com/MapServer/MapServer/files/14053438/data.zip)

**Comment by geographika** [comment] 2024-02-11 19:40
@ltclm - thanks for providing a fully working test case. I can confirm the issue still exists in the MapServer main branch. 
The issue is that the Map extent is modified at various points in the WMS code, and then the map drawing code. At some point the search rectangle used for selecting features is moved from the extent passed in the original request. 

This can be seen in the image below. The orange area is the original request extent, and the pink is the extent used to select the underlying features. As you can see in the image only the lower two features intersect, and so are the only features drawn. 

![image](https://github.com/MapServer/MapServer/assets/490840/5ae10c9e-569a-4103-a983-76155c6531e7)

It is harder to pin down which of the various modifications to the extent is the cause of the shift, and why this may be necessary.

**Comment by geographika** [comment] 2024-02-11 21:35
This appears to be a projection issue, and possibly related to #6479 and #6478. 

Setting `int apply_over = MS_FALSE;` in the following code brings back the correct results:

https://github.com/MapServer/MapServer/blob/da769fc2e71644415160342a1bc125b6127c3f54/src/mapproject.c#L1902

![image](https://github.com/MapServer/MapServer/assets/490840/e20979dc-1f05-4f96-923e-10f199a5c597)

**Comment by ltclm** [comment] 2024-02-12 08:36
thank you @geographika for your response, the insights and the link to the related issues :+1: 
i can confirm that changing the projection of the layer from 
```
"init=epsg:2056"
```
to 
```
"+proj=somerc +lat_0=46.9524055555556 +lon_0=7.43958333333333 +k_0=1 +x_0=2600000 +y_0=1200000 +ellps=bessel +towgs84=674.374,15.056,405.346,0,0,0,0 +units=m +no_defs +type=crs"
```
as proposed here https://github.com/MapServer/MapServer/issues/6478#issuecomment-1039579726 is fixing the projection issue.
as a short time measure we will be using this workaraound in the wms configuration.

**Comment by mizzPpY** [comment] 2024-03-07 07:29
Hi @ltclm ,
this comment is not related to the original issue, but I would like to know how does your mapserver dockerfile and deployment file looks like?

I was using `camptocamp/mapserver:7.4` image deploy on kubernetes cluster, it was working fine but encounter issue updating to 8.0. When curl http://localhost it is returning status 500 instead of the usual response "No query information to decode. QUERY_STRING is set, but empty.". 

Had been looking everywhere what is causing the upgrade failure but couldn't find any answer, since I saw you using the same image and able to at least get something, I hope you can provide some insight for me.
Thank you.

**Comment by geographika** [comment] 2024-06-04 21:21
@oshawa-connection-jacobs - I'm not aware of anyone actively looking at this, and there are no relevant commits to [mapproject.c](https://github.com/MapServer/MapServer/commits/main/src/mapproject.c) that aren't already in the 8.0.1 release (if this is where the issue lies). It would be great if you can provide any more insight into the issue.

**Comment by ltclm** [comment] 2024-06-06 08:36
a fix of this would be highliy appreciated by us too. we are currently running a custom built of mapserver 7.6.5 where we have set `int apply_over = MS_FALSE` (as proposed as workaround in this issue). 

This seems to solve the disappearing features in reprojected getmap requests. But requests lead from time to time to core dumps, especially under load. So the requests or the pattern is hard to reproduce and share. we had to disable the core dumps in our k8s setup to prevent the ephemeral storage to be completely consumed.

**Comment by oshawa-connection** [comment] 2024-06-07 19:14
I've dug a bit into my problem I was having with mapserver 8.0.1 with proj version 9. 

When I take the code from the gzipped 8.0.1 release, build that with proj v9, I get a similar (though not the same)  problem as above. When I clone from main branch, it works perfectly.

When I step through the msProjectRect function with the 8.0.1 release + proj v9, it doesn't change the bbox at all, so I assume my seperate problem must be elsewhere and fixed by some commit to a different file that was merged since November.

@geographika  when you replicated this problem, were you using the code directly from main branch, or from the gzipped mapserver release, and which proj version? 

Screenshots of my example, now fixed by cloning mapserver main branch and using proj V9. That should also prevent others from having to do workarounds too, so long as you don't mind using non-official released code.

![image](https://github.com/MapServer/MapServer/assets/36929345/e73d2f4c-835e-43ce-b1c3-d84e811eb086)
![image](https://github.com/MapServer/MapServer/assets/36929345/23293a00-1de6-49e9-aeb9-357ecdfa7a33)

**Comment by geographika** [comment] 2024-06-08 10:04
@oshawa-connection - I would have been using the main branch and PROJ9, but I don't know what changes could have affected this since February when I could recreate the original issue.

**Comment by oshawa-connection** [comment] 2024-06-09 08:27
I think the issue I was having was similar, but unrelated to this issue - sorry for the confusion. If I take that swiss data example I do indeed get the same behavior using main branch.

**Comment by oshawa-connection** [comment] 2024-06-09 15:24
Sorry for the message spam, I think I have solved @ltclm 's original problem too, I have created a PR for it here: #7074 

The source of this problem was a workaround in mapserver for a bug in proj prior to version 9.4.1. The workaround checks for  proj major versions between 6 and 9, and then applies a fix. However, versions 9.0 through 9.4.0 suffer from the original proj bug, and do not have the workaround applied. 

Proj 9.4.0 is the version that gets installed when using the latest GDAL docker image, which hopefully explains why you were having the problem.

The long term solution is to upgrade to proj 9.4.1, which unfortunately atm means installing proj from source, hopefully that's not too painful for you. Or alternatively, downgrade to any proj version 8.

Here is that 4 polygon layer under proj 9.4.1 when really zoomed in, using proj 9.4.1
![image](https://github.com/MapServer/MapServer/assets/36929345/f8b1695c-5ed2-4482-9973-53c0d173910c)

**Comment by ltclm** [comment] 2024-06-11 14:41
thank you very much @oshawa-connection for your fix.
I have applied the same patch on `src/mapproject.c` in our `7.6.5 mapserver` [1] installation and it seems to work fine :+1: 

[1]
```text
# mapserv -v
MapServer version 7.6.5 OUTPUT=PNG OUTPUT=JPEG OUTPUT=KML SUPPORTS=PROJ SUPPORTS=AGG SUPPORTS=FREETYPE SUPPORTS=CAIRO SUPPORTS=SVG_SYMBOLS SUPPORTS=RSVG SUPPORTS=ICONV SUPPORTS=FRIBIDI SUPPORTS=WMS_SERVER SUPPORTS=WMS_CLIENT SUPPORTS=WFS_SERVER SUPPORTS=WFS_CLIENT SUPPORTS=WCS_SERVER SUPPORTS=SOS_SERVER SUPPORTS=FASTCGI SUPPORTS=GEOS SUPPORTS=POINT_Z_M SUPPORTS=PBF INPUT=JPEG INPUT=POSTGIS INPUT=OGR INPUT=GDAL INPUT=SHAPEFILE

Rel. 9.4.0, March 1st, 2024

GDAL 3.8.5, released 2024/04/02
```

**Closed** 2024-07-21 11:17 UTC

**Comment by ltclm** [comment] 2024-08-14 13:12
@rouault thank you very much for the fix.

I can still reproduce the issue here with mapserver 8.2.1 
```
mapserv -v
MapServer version 8.2.1 PROJ version 9.4 GDAL version 3.8 OUTPUT=PNG OUTPUT=JPEG OUTPUT=KML SUPPORTS=PROJ SUPPORTS=AGG SUPPORTS=FREETYPE SUPPORTS=CAIRO SUPPORTS=SVG_SYMBOLS SUPPORTS=RSVG SUPPORTS=ICONV SUPPORTS=FRIBIDI SUPPORTS=WMS_SERVER SUPPORTS=WMS_CLIENT SUPPORTS=WFS_SERVER SUPPORTS=WFS_CLIENT SUPPORTS=WCS_SERVER SUPPORTS=SOS_SERVER SUPPORTS=OGCAPI_SERVER SUPPORTS=FASTCGI SUPPORTS=GEOS SUPPORTS=PBF INPUT=JPEG INPUT=POSTGIS INPUT=OGR INPUT=GDAL INPUT=SHAPEFILE INPUT=FLATGEOBUF
```

the issue can be reproduced as described here in this ticket with this getmap request:
```
?map=/etc/mapserver/wms.map&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=47.7172290358096447,8.65006363064953554,47.71931501123628294,8.652714418911338967&CRS=EPSG:4326&WIDTH=1591&HEIGHT=1253&LAYERS=test&STYLES=&FORMAT=image/jpeg&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96
```

I am using this docker file [1] which is a slightly modified version of c2c Dockerfile here [2].

do i have to change something in the mapfile itself too?

best regards

[1] 
```Dockerfile
FROM ghcr.io/osgeo/gdal:ubuntu-small-3.8.5 as gdal

FROM gdal as builder
LABEL maintainer Camptocamp "info@camptocamp.com"
SHELL ["/bin/bash", "-o", "pipefail", "-cux"]

RUN --mount=type=cache,target=/var/cache,sharing=locked \
    --mount=type=cache,target=/root/.cache \
    apt-get update \
    && apt-get upgrade --assume-yes \
    && DEBIAN_FRONTEND=noninteractive apt-get install --assume-yes --no-install-recommends bison \
        flex python3-lxml libfribidi-dev swig \
        cmake librsvg2-dev colordiff libpq-dev libpng-dev libjpeg-dev libgif-dev libgeos-dev libgd-dev \
        libfreetype6-dev libfcgi-dev libcurl4-gnutls-dev libcairo2-dev libxml2-dev \
        libxslt1-dev python3-dev php-dev libexempi-dev lcov lftp ninja-build git curl \
        clang libprotobuf-c-dev protobuf-c-compiler libharfbuzz-dev libcairo2-dev librsvg2-dev \
    && ln -s /usr/local/lib/libproj.so.25 /usr/local/lib/libproj.so

ARG MAPSERVER_BRANCH=branch-8-2
ARG MAPSERVER_REPO=https://github.com/mapserver/mapserver

RUN git clone ${MAPSERVER_REPO} --branch=${MAPSERVER_BRANCH} --depth=100 /src
# the branch here was at commit a9981b422

ARG WITH_ORACLE=OFF

WORKDIR /src/build

RUN  cmake .. \
    -GNinja \
    -DCMAKE_C_FLAGS="-O2 -DPROJ_RENAME_SYMBOLS" \
    -DCMAKE_CXX_FLAGS="-O2 -DPROJ_RENAME_SYMBOLS" \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=/usr/local \
    -DWITH_CLIENT_WMS=1 \
    -DWITH_CLIENT_WFS=1 \
    -DWITH_OGCAPI=1 \
    -DWITH_KML=1 \
    -DWITH_SOS=1 \
    -DWITH_XMLMAPFILE=1 \
    -DWITH_CAIRO=1 \
    -DWITH_RSVG=1 \
    -DUSE_PROJ=1 \
    -DUSE_WFS_SVR=1 \
    -DUSE_OGCAPI_SVR=1 \
    -DWITH_ORACLESPATIAL=${WITH_ORACLE}


RUN ninja install

FROM gdal as runner
LABEL maintainer Camptocamp "info@camptocamp.com"
SHELL ["/bin/bash", "-o", "pipefail", "-cux"]

# Let's copy a few of the settings from /etc/init.d/apache2
ENV APACHE_CONFDIR=/etc/apache2 \
    APACHE_ENVVARS=/etc/apache2/envvars \
    # And then a few more from $APACHE_CONFDIR/envvars itself
    APACHE_RUN_USER=www-data \
    APACHE_RUN_GROUP=www-data \
    APACHE_RUN_DIR=/var/run/apache2 \
    APACHE_PID_FILE=/var/run/apache2/apache2.pid \
    APACHE_LOCK_DIR=/var/lock/apache2 \
    APACHE_LOG_DIR=/var/log/apache2 \
    LANG=C \
    TERM=linux \
    MS_MAP_PATTERN=^\\/etc\\/mapserver\\/([^\\.][-_A-Za-z0-9\\.]+\\/{1})*([-_A-Za-z0-9\\.]+\\.map)$

RUN --mount=type=cache,target=/var/cache,sharing=locked \
    --mount=type=cache,target=/root/.cache \
    apt-get update \
    && apt-get upgrade --assume-yes \
    && apt-get install --assume-yes --no-install-recommends ca-certificates apache2 libapache2-mod-fcgid \
        libfribidi0 librsvg2-2 libpng16-16 libgif7 libfcgi0ldbl \
        libxslt1.1 libprotobuf-c1 libaio1 libpcre2-posix3 glibc-tools

RUN a2enmod fcgid headers status \
    && a2dismod -f auth_basic authn_file authn_core authz_user autoindex dir \
    && rm /etc/apache2/mods-enabled/alias.conf \
    && mkdir --mode=go+w --parent ${APACHE_RUN_DIR} ${APACHE_LOCK_DIR} \
    && mkdir --parent /etc/mapserver \
    && chmod o+w /var/lib/apache2/fcgid /var/lib/apache2/fcgid/sock \
    && find "$APACHE_CONFDIR" -type f -exec sed -ri ' \
    s!^(\s*CustomLog)\s+\S+!\1 /proc/self/fd/1!g; \
    s!^(\s*ErrorLog)\s+\S+!\1 /proc/self/fd/2!g; \
    ' '{}' ';' \
    && sed -ri 's!LogFormat "(.*)" combined!LogFormat "%{us}T %{X-Request-Id}i \1" combined!g' /etc/apache2/apache2.conf \
    && echo 'ErrorLogFormat "%{X-Request-Id}i [%l] [pid %P] %M"' >> /etc/apache2/apache2.conf \
    && sed -i -e 's/<VirtualHost \*:80>/<VirtualHost *:8080>/' /etc/apache2/sites-available/000-default.conf \
    && sed -i -e 's/Listen 80$/Listen 8080/' /etc/apache2/ports.conf \
    && rm -rf /etc/apache2/conf-enabled/other-vhosts-access-log.conf

EXPOSE 8080

COPY --from=builder /usr/local/bin /usr/local/bin/
COPY --from=builder /usr/local/lib /usr/local/lib/
COPY --from=builder /usr/local/share/mapserver /usr/local/share/mapserver/
COPY --from=builder /src/share/ogcapi/templates/html-bootstrap4 /usr/local/share/mapserver/ogcapi/templates/html-bootstrap4/

COPY runtime /

RUN ldconfig

ENV MS_DEBUGLEVEL=0 \
    MS_ERRORFILE=stderr \
    MAPSERVER_CONFIG_FILE=/etc/mapserver.conf \
    MAPSERVER_BASE_PATH= \
    MAX_REQUESTS_PER_PROCESS=1000 \
    MIN_PROCESSES=1 \
    MAX_PROCESSES=5 \
    BUSY_TIMEOUT=300 \
    IDLE_TIMEOUT=300 \
    IO_TIMEOUT=40 \
    GET_ENV=env

CMD ["/usr/local/bin/start-server"]

WORKDIR /etc/mapserver

```
[2] https://github.com/camptocamp/docker-mapserver/blob/master/Dockerfile
