### ISSUE TITLE
Mapserver 7 Label with Outlinecolor

### ISSUE THREAD

**Issue by wirkus** [mapserver/mapserver#5097] opened 2015-05-08 12:48 UTC
Hello,
I'm testing Mapserver7 and have problems with LABELs. I use SIZEUNITS meters, OUTLINECOLOR 253 253 253, OUTLINEWIDTH 1. 
In large scale range the outline is displayed very large. There is no way to reduce the size of the OUTLINECOLOR. We tried OUTLINECOLORMINWIDTH/OUTLINECOLORMAXWIDTH but this parameter is not supported.

Best regards

**Comment by ejn** [comment] 2015-05-08 13:10
I think this is a duplicate of #4942 - which was closed with commit d0043f2 on 27th March. Please check from when your Mapserver 7 version is and whether that commit is included, and close this ticket if appropriate.

**Comment by tbonfort** [comment] 2015-07-16 08:59
assuming fixed with #5107, reopen if necessary

**Closed by tbonfort** 2015-07-16 08:59 UTC
