### ISSUE TITLE
getlegendgraphic requests fails with geomtransform in layer class

### ISSUE THREAD

**Issue by ltclm** [mapserver/mapserver#5300] opened 2016-07-08 09:25 UTC
A GetLegend Request [1] on the following layer [2] ends up with an 500 error.
It seems to be related to the GEOMTRANSFORM configuration in the Layer classes.
Without the geomtransform the getlegend request is working fine. 
We are using mapserver 6.4.1, currently we have disabled the getlegendgraphic request from this layer, but it would be good to know why this is not working.

[1]
http://wms.geo.admin.ch/?version=1.3.0&service=WMS&request=GetLegendGraphic&sld_version=1.1.0&layer=ch.bav.sachplan-infrastruktur-schiene_anhorung_polygons_pl&format=image/png&STYLE=default

apache error.log
```
[Fri Jul 08 11:18:23 2016] [warn] [client 10.220.4.250] mod_fcgid: error reading data, FastCGI server closed connection
[Fri Jul 08 11:18:23 2016] [error] [client 10.220.4.250] Premature end of script headers: mapserv
```

[2] Layer configuration
```
LAYER
    CONNECTION "user=xxx password=xxx host=xxx dbname=xxx port=5432 options='-c client_encoding=UTF8'"
    CONNECTIONTYPE POSTGIS
    DATA "the_geom from  (SELECT *  from bav.sis_pl_anhorung WHERE geom_type like '%area%') as data using unique stabil_id using srid=21781"
    GROUP "ch.bav.sachplan-infrastruktur-schiene_anhorung"
    NAME "ch.bav.sachplan-infrastruktur-schiene_anhorung_polygons_pl"
    STATUS OFF
    MAXSCALEDENOM 499999
    MINSCALEDENOM 25000
    TEMPLATE "ttt"
    TYPE POLYGON
    UNITS METERS
    CLASS
      NAME "pl_poly_fest_m02"
      EXPRESSION ('[meastype_tid]' eq '71-M-02' AND '[coordlevel_tid]' eq 'cl1')
      STYLE
        COLOR 226 0 26
        OPACITY 60
        GEOMTRANSFORM (buffer([shape],3))
      END
    END
    CLASS
      NAME "pl_poly_zwi_m02"
      EXPRESSION ('[meastype_tid]' eq '71-M-02' AND '[coordlevel_tid]' eq 'cl2')
      STYLE
        COLOR 238 126 34
        GEOMTRANSFORM (buffer([shape],3))
        OPACITY 60
      END
    END
    CLASS
      NAME "pl_poly_vor_m02"
      EXPRESSION ('[meastype_tid]' eq '71-M-02' AND '[coordlevel_tid]' eq 'cl3')
      STYLE
        COLOR 255 237 0
        OPACITY 60
        GEOMTRANSFORM (buffer([shape],3))
      END
    END

```

**Comment by tbonfort** [comment] 2016-07-08 09:28
duplicate of #5193 #5233. I don't think those patches have been backported to 6.4

**Comment by ltclm** [comment] 2016-07-08 09:34
thanks for the feedback, thus we will plan to upgrade to mapserver 7 soon.

**Closed** 2016-08-27 09:28 UTC
Labels: Duplicate, MapServer C Library
