### ISSUE TITLE
msTileSetup(): CGI error. Tile API is not available.

### ISSUE THREAD

**Issue by OrlovDiga** [MapServer/MapServer#6178] opened 2020-11-18 10:07 UTC
Hello, I have a problem with MapServer with mode = tile. With such a request: http://127.0.0.1/cgi-bin/mapserv?map=/Users/macbook/mvt-demo/demo.map&mode=tile (it's a simple example without params), I get this error 
![image](https://user-images.githubusercontent.com/43121141/99512758-e47c8400-299a-11eb-97df-fc36ff1aee4b.png) 
Initially, I installed the binary MapServer, but after that, I downloaded the source code and compiled from it (version 7.6.1). This is how I configure the application (by [tutorial](https://mapserver.org/installation/unix.html)):
1) cd MapServer-7.6.1
2) mkdir build
3) cd build
4)cmake -DCMAKE_INSTALL_PREFIX=/opt \
        -DCMAKE_PREFIX_PATH=/usr/local/pgsql/91:/usr/local:/opt \
        -WITH_PROJ=ON \
        -WITH_GDAL=ON \
        -WITH_OGR=ON \
        -WITH_FRIBIDI=ON \
        -DWITH_CLIENT_WFS=ON \
        -DWITH_CLIENT_WMS=ON \
        -DWITH_CURL=ON \
        -DWITH_SOS=ON \
        -DWITH_PHP=ON \
        -DWITH_PERL=OFF \
        -DWITH_RUBY=OFF \
        -DWITH_JAVA=OFF \
        -DWITH_CSHARP=OFF \
        -DWITH_PYTHON=OFF \
        -DWITH_SVGCAIRO=OFF \
        -DWITH_ORACLESPATIAL=OFF \
        -DWITH_MSSQL2008=OFF \
        ../ >../configure.out.txt
5) make
6) make install
And after that I try again to get the response to the get request, but I also get an error.

I found where exactly in the [source code](https://github.com/MapServer/MapServer/blob/master/maptile.c) This error is thrown (find by control + f "Tile API is not available."). This error occurs if USE_TILE_API is undefined or has 0. In this case, I think it is simply undefined.
Thus, I think that the [source file](https://github.com/MapServer/MapServer/blob/master/maptile.h) where USE_TILE_API is being initialized simply cannot be found due to the wrong paths.

Am I missing something or could there really be some mistake in the source code?

P.S. For an example of a MapServer with support for tiles, I used [this repository](https://github.com/sdlime/mvt-demo) and accessed it exactly

I would be grateful for any answer and advice.

**Comment by OrlovDiga** [comment] 2020-11-18 11:40
I managed to get rid of the problem, after that, I have a map displayed on the client. But I don't think there is a good solution. Since in my opinion this flag should be set automatically at startup. Can someone say something on this topic?

cmake -DCMAKE_INSTALL_PREFIX=/opt
         -DCMAKE_PREFIX_PATH=/usr/local/pgsql/91:/usr/local:/opt
         -WITH_PROJ=ON
         -WITH_GDAL=ON
         -WITH_OGR=ON
         -WITH_FRIBIDI=ON
         -DWITH_CLIENT_WFS=ON
         -DWITH_CLIENT_WMS=ON
         -DWITH_CURL=ON
         -DWITH_SOS=ON
         -DWITH_PHP=ON
         -DWITH_PERL=OFF
         -DWITH_RUBY=OFF
         -DWITH_JAVA=OFF
         -DWITH_CSHARP=OFF
         -DWITH_PYTHON=OFF
         -DWITH_SVGCAIRO=OFF
         -DWITH_ORACLESPATIAL=OFF
         -DWITH_MSSQL2008=OFF
         -DCMAKE_C_FLAGS="-DUSE_TILE_API"
         ../ >../configure.out.txt

**Comment by jmckenna** [comment] 2020-11-18 11:46
@OrlovDiga please send your questions direct to the MapServer community (where 1000+ readers exist to help) in the mapserver-users forum: subscribe at https://lists.osgeo.org/listinfo/mapserver-users    Github is not for support questions.  Thanks.

**Comment by sdlime** [comment] 2020-11-18 15:17
Jeff, actually I think this represents a bug. The Tile API is basically a default bit of functionality as long as Proj is found and since Proj is a required dependency it should always be available. Anyway, maptile.h has this bit at the top:

```
#ifdef USE_PROJ
#define USE_TILE_API 1
#endif
```

Looking at the CMakeLists.txt file in the 7.6 branch I don't see the USE_PROJ symbol being set. I think we could probably just remove the USE_PROJ check but let's ping @rouault for his thoughts. This would be a candidate for a backport.

@OrlovDiga, I saw you brought this up on my mvt-demo repo as well. You're immediate work arounds (I think) would be to:

1. Revert and use MapServer 7.4.
2. Edit maptile.h and remove the USE_PROJ check (but keep the USE_TILE_API line), then recompile.

--Steve

**Comment by jmckenna** [comment] 2020-11-18 15:31
Thanks Steve!  appreciate your feedback.  Marking this as a bug.

**Comment by dmorissette** [comment] 2020-11-18 15:52
I confirm the bug and that the fix is to remove the #ifdef USE_PROJ. We had come across this issue and I had on my TODO list to submit a pull request with a corresponding test, but haven't found the time yet.

There is currently no mode=tile test in msautotest, so in case someone wants to tackle this, here is a test that could be added as msautotest/misc/mode_tile.map and that can be used to reproduce the issue and verify the fix. (the file was renamed with a .txt extension only to upload it in this issue)

[mode_tile.map.txt](https://github.com/MapServer/MapServer/files/5561158/mode_tile.map.txt)

**Comment by jmckenna** [comment] 2020-11-18 16:11
ah, for other readers: this was initially reported a few days ago and discussed as a bug in https://github.com/sdlime/mvt-demo/issues/6

**Comment by jmckenna** [comment] 2020-11-18 16:36
Now I realize when I did all the mode=tileset testing for all of the recent updates to the doc (https://mapserver.org/output/tile_mode.html) I used the main/master branch, yikes, good catch @OrlovDiga   Sorry for not catching this sooner.

**Closed** 2020-12-07 17:42 UTC
Labels: Bug, backport branch-7-6
