### ISSUE TITLE
MAXLENGTH < 0 returns 'internal server error'

### ISSUE THREAD

**Issue by m431m** [mapserver/mapserver#5156] opened 2015-09-01 13:28 UTC
Hi,
It's all in the title ! (in mapserver 7 beta)
m431m

**Comment by tbonfort** [comment] 2015-09-07 13:56
This is a regression from previous 6.x versions, c.f. https://github.com/mapserver/mapserver/blob/rel-7-0-0/textlayout.c#L559
I don't see this getting fixed in the near future for the reasons detailed in the comment as it is too much work for an unfunded issue. If you absolutely need the functionality, you should preprocess your labels from
```
Text: "The text I need to hard wrap"
MAXLENGTH -5
```
to
```
Text: "The t#ext I#need #to ha#rd wr#ap"
WRAP "#"
```

**Comment by m431m** [comment] 2015-09-07 14:42
Yes, use case is quite special.
So if this workaround is suitable for the needs of all users...
Perhaps a note should be added to the documents to indicate this forced obsolescence...

**Comment by tbonfort** [comment] 2015-09-08 08:13
note added to docs and migration guide.
on a side note, your comment implying "forced obsolescence" is disrespectful and does not apply to this situation as AFAIK the existing versions still support this.

**Closed by tbonfort** 2015-09-08 08:13 UTC
Labels: MapServer C Library

**Comment by m431m** [comment] 2015-09-08 08:31
Hi Thomas, Thank you for taking the time to added note.
I misspoke (my english is not good...). Don't take this the wrong way. 
m431m

**Comment by tbonfort** [comment] 2015-09-08 08:40
thanks for clarifying @m431m , no offense taken then
