### ISSUE TITLE
Default MetadataURL attribute type value does not validate

### ISSUE THREAD

**Issue by Headingwest14** [mapserver/mapserver#5751] opened 2019-02-26 23:14 UTC
We ran into an XML validation issue with the MetadataURL type default value, "ISOTC211/19115", that is referenced at https://www.mapserver.org/ogc/layer_metadata.html. 
It looks like the http://schemas.opengis.net/wms/1.3.0/capabilities_1_3_0.xsd defines the type attribute as an "NMTOKEN". NMTOKEN does not allow "/" (forward slashes), and our XML validation complains and throws the error:
    
SystemID: *****.xml
Engine name: Xerces
Severity: error
Description: cvc-attribute.3: The value 'ISOTC211/19115' of attribute 'type' on element 'MetadataURL' is not valid with respect to its type, 'NMTOKEN'.
Start location: 294:27
End location: 294:43
URL: http://www.w3.org/TR/xmlschema-1/#cvc-attribute
​​
I was wondering if you could change the default value from ISOTC211/19115 to ISOTC211_19115 or something similar. When I changed the / to an _ the capabilities document validated.

**Comment by tomkralidis** [comment] 2019-02-27 11:49
@Headingwest14 thanks for the report.  I'm unable to reproduce.  The value `ISOTC211/19115` is only used when emitting `GetMetadata` requests.  Any `MetadataURL/@type` values in Capabilities metadata would be part of the server configuration of the given WMS.

**Comment by Headingwest14** [comment] 2019-02-28 16:00
@tomkralidis Thanks for checking into this Tom, Unfortunately, the WMS service isn't ours so I don't have the .map file to check. I will ask them to check their .map file to see if wms_metadataurl_type is set. One reason we thought it might be a default setting is that the "How it works section" on the https://www.mapserver.org/ogc/layer_metadata.html page seems to say that if no metadata tags are set Mapserver will provide a metadata link in the getcapabilities. I will check in with the WMS owner to see if I can figure out the issue. The capbilities file in question is: https://geoegl.msp.gouv.qc.ca/ws/mffpecofor.fcgi?request=getCapabilities&version=1.1.1&service=wms

Thanks again.

**Comment by tomkralidis** [comment] 2019-02-28 16:03
Thanks @Headingwest14. Looks like a typo in the docs, will fix.  Closing given it's a provider metadata issue.

**Closed by tomkralidis** 2019-02-28 16:03 UTC
