### ISSUE TITLE
pagination with ogcapi doesnt work in demo server

### ISSUE THREAD

**Issue by landryb** [MapServer/MapServer#6613] opened 2022-09-14 13:14 UTC
https://demo.mapserver.org/cgi-bin/mapserv/localdemo/ogcapi/collections/countries/items?limit=10 and https://demo.mapserver.org/cgi-bin/mapserv/localdemo/ogcapi/collections/countries/items?f=html&limit=10&offset=10 give the exact same features..
## Expected behavior and actual behavior.

the features returned should properly paginate on the complete dataset..
and the same problem seems to affect json output ?

eg https://demo.mapserver.org/cgi-bin/mapserv/localdemo/ogcapi/collections/countries/items?f=json&limit=10 & https://demo.mapserver.org/cgi-bin/mapserv/localdemo/ogcapi/collections/countries/items?f=json&limit=10&offset=10 give the same result.

i don't know what dataset type is used for countries, but it smells fishy. And the problem is the same for other collections on the demo service.

@sdlime @jmckenna ?

## MapServer version and installation method

well ms4w head i guess..

**Comment by sdlime** [comment] 2022-09-14 15:22
Jeff, were can the demo service files be found?

**Comment by jmckenna** [comment] 2022-09-14 15:25
I likely use old templates (I assumed this problem might happen).  I'll update the templates, from the latest ones in the `main` branch.  @landryb does this problem occur for your own local service?

**Comment by sdlime** [comment] 2022-09-14 15:30
It looks like the offset param has no affect - you can just try with JSON (so independent of the templates) and you always get the same set of results back. It certainly worked at some point. @jmckenna or @landryb, can you confirm what I'm seeing?

**Comment by geographika** [comment] 2022-09-14 15:32
@sdlime - I can confirm on my side - same results no matter what the offset parameter.

**Comment by jmckenna** [comment] 2022-09-14 15:40
I also confirm locally here.  (it seems to not be just a demo issue) @landryb can you confirm this issue locally?

**Comment by sdlime** [comment] 2022-09-14 15:51
@landryb did in the original ticket. I missed that at first.

**Comment by jmckenna** [comment] 2022-09-14 16:59
ok, so to summarize: @sdlime @geographika and myself can duplicate this locally with main, using our own individual service, but @landryb cannot reproduce this with `main`, just with demo, correct?

**Comment by landryb** [comment] 2022-09-15 06:28
sorry havent had time to try reproducing locally with 8.0.0, i've seen it on demo but i havent checked yet other instances. I'm also pretty sure the offset parameter worked at some point. Might be dependent on dataset type being used ?

**Comment by landryb** [comment] 2022-09-15 07:55
with plain 8.0.0 on OpenBSD, and a flatgeobuf CONNECTIONTYPE or a shapefile DATA, offset parameter works fine and i have proper pagination. @sdlime @jmckenna @geographika when you reproduced, that was only against sql datasets ? since #6617 mentions 'database drivers' ....

**Comment by jratike80** [comment] 2022-09-15 08:01
As far as I know there is no offset in the OGC API Features. There is no shortcut into a page that it not the first one, users are supposed to read the first page and follow the next links.

The motivation for this change that OGC did compared to the WFS 2.0 StartIndex + Count was practical. While those parameters feel to convert nicely into for example `LIMIT` and `OFFSET` for PostGIS, unfortunately such database queries tend to be very slow when the OFFSET is huge.

**Comment by landryb** [comment] 2022-09-15 08:13
there's 'limit' in https://docs.opengeospatial.org/is/17-069r3/17-069r3.html#_parameter_limit, 'offset' is mentioned in the examples, and afaict supported by qgis server & mapserver - but not by geoserver ? so that's a vendor extension ?

**Comment by jratike80** [comment] 2022-09-15 08:16
If I read the examples right, `offset` appears only within the next links, not as a query parameter.

**Comment by landryb** [comment] 2022-09-15 08:20
opengeospatial/OGC-Web-API-Guidelines#12 mentions that it should be left to the implementer's choice. anyway, whatever the parameter used/chosen, the 'next'/'prev' links on demo.mapserver.org dont work ;)

afaict, pygeoapi also chose `offset`.

**Comment by geographika** [comment] 2022-09-15 08:34
> with plain 8.0.0 on OpenBSD, and a flatgeobuf CONNECTIONTYPE or a shapefile DATA, offset parameter works fine and i have proper pagination. @sdlime @jmckenna @geographika when you reproduced, that was only against sql datasets ? since #6617 mentions 'database drivers' ....

I've only tested with database drivers. Maybe file datasets rely on `map->query.startindex = 1 + offset;` - which was already present in the codebase, and could explain why these work.

**Comment by jratike80** [comment] 2022-09-15 08:35
Yes, using `offset` is practical but the downside is real if it is used blindly to create next links which the OAPIF server is just sending to the database
```
limit 1000 offset 0
limit 1000 offset 1000
limit 1000 offset 2000
```
See a diagram in https://www.eversql.com/faster-pagination-in-mysql-why-order-by-with-limit-and-offset-is-slow/. However, developers can do it in a better way on the server side also with a parameter called "offset" and I have nothing against it. It would be a practical extension to the standard but I would suggest that OAPIF developers are not allowed to test paging with collections that have less than let's say one million features, and paging must be tested always till the last page and with a stopwatch ;)

**Comment by jratike80** [comment] 2022-09-15 09:07
I write down here a result of a quick test with GeoPackage to point out that it has a meaning how the server does the paging. This query i fast always with any fid value and takes around 0.06 sec.
```
select * from rakennus
where fid>5100000
limit 1000
```
This is as fast when the offset is 0 but takes 1.94 sec when the offset is 5100000
```
select * from 
rakennus
limit 1000
offset 5100000
```
If user reads 5000 pages for getting the whole collection and waits 0.9 sec on average while the service applies limits and offsets it would make **4500** seconds in total, that is **one hour and 15 minutes**. Calculation is based on an untested hypothesis that the growth is linear.

**Comment by jmckenna** [comment] 2022-09-19 19:41
@landryb could you also confirm the fix through #6617 with your local services?

Here it is on the demo server now:

https://demo.mapserver.org/cgi-bin/mapserv/localdemo/ogcapi/collections/countries/items?f=html&limit=10&offset=10

versus

https://demo.mapserver.org/cgi-bin/mapserv/localdemo/ogcapi/collections/countries/items?limit=10

**Comment by jmckenna** [comment] 2022-09-19 19:44
ah sorry @landryb you weren't using databases in testing :)  Anyway it looks good here in my testing.

**Comment by landryb** [comment] 2022-09-20 08:08
i havent tested #6617 locally but yes it makes sense, this way databases will have proper pagination with OGCAPI in 8.0.1

**Comment by jmckenna** [comment] 2022-09-21 12:48
closing, as this seems fixed in `main`

**Closed by jmckenna** 2022-09-21 12:48 UTC
Labels: Bug, OGCAPI: Features
