### ISSUE TITLE
DXF through WFS request extension

### ISSUE THREAD

**Issue by zanollim** [mapserver/mapserver#4583] opened 2013-02-04 13:58 UTC
I'm exporting DXF files from Postgresql database using ogr2ogr.
Now I'm interested to use WFS requests through Mapserver to generate the same DXF files.

I need to pass to the OGR library the following dataset creation option:
`-dsco HEADER=/opt/scripts/catalogo/header.dxf`
    
In the documentation I've read that I can put inside the OUTPUTFORMAT section the following line:
`FORMATOPTION "DSCO:HEADER=/opt/scripts/catalogo/header.dxf"`

Good, it works!

But I need two other parameters:
`--config DXF_WRITE_HATCH NO
-select 'a list of fields to be included separated by space'
`

The first is a general configuration option, the second is an ogr2ogr parameter.
How can I put these parameters for DXF creation inside Mapserver?
For example:
`FORMATOPTION "SELECT:a list of fields to be included separated by space"`

NOTE: I need the '-select' option to say OGR to not include any field when creating DXF, otherwise OGR (and so Mapserver) returns an error like this:
`msOGRWriteFromQuery(): OGR error. Failed to create field 'codice' in output feature schema: DXF layer does not support arbitrary field creation, field 'codice' not created`

**Comment by jratike80** [comment] 2015-11-10 10:19
I believe that "--config DXF_WRITE_HATCH NO"  part you could do by setting an environmental variable in mapfile at MAP level or in the Apache conf. For selecting just some attributes from WFS you could use the standard WFS way is to add &PROPERTYNAME=attr1,attr2 into the GetFeature request.

I am closing because I consider that this is not a bug. Questions should be sent to mapserver-users mailing list.

**Closed by jratike80** 2015-11-10 10:19 UTC
