### ISSUE TITLE
GRID layer with no label block crashes MapServer > v 7.0.4

### ISSUE THREAD

**Issue by cnieman** [mapserver/mapserver#5466] opened 2017-07-24 13:57 UTC
I am trying to draw a map with a grid layer that has no labels.

If I put in an empty label block, the map works with the label defaults for font, size, color, etc. But, if I comment out the label block, I get a crash.  The grid with no label block works with MapServer 7.0.4 , but not MapServer 7.0.6, branch-7.0, or master.

I've attached a test mapfile, and the GDB output I got with a build from master.

[test.map.txt](https://github.com/mapserver/mapserver/files/1169974/test.map.txt)
[gdb.txt](https://github.com/mapserver/mapserver/files/1169997/gdb.txt)

**Comment by sdlime** [comment] 2017-07-28 19:45
Hi @cnieman: Thanks for the test case, I'll have a look. --Steve

**Comment by sdlime** [comment] 2017-08-02 14:40
What happens if you don't set the label format? --Steve

**Comment by cnieman** [comment] 2017-08-02 15:04
I still get a crash with no labelformat in the GRID object.

**Comment by sdlime** [comment] 2017-08-02 16:31
I think this is something more fundamental associated with grids and the calls in the gdb output are a red herring. Personally I think we should turn labeling off if the labelformat is set to "".

**Comment by cnieman** [comment] 2017-08-02 17:09
To clarify, the way we are using the grid is to get the intersections and labels from msGraticuleLayerGetIntersectionPoints to insert labels into a PDF around the map, so that's why I have a LABELFORMAT, but no LABEL block in my example.  We don't want labels on the map, we place them around the map with custom code that formats them as we want and inserts the map into an SVG.

I believe leaving the LABELFORMAT out would result in not getting appropriate grid values from msGraticuleLayerGetIntersectionPoints. See attached images.

**With LABELFORMAT "%g"**
![With LABELFORMAT](https://user-images.githubusercontent.com/1630425/28885231-216590e6-7783-11e7-8e38-b16b401919c3.png)

**With LABELFORMAT line commented out**
![With LABELFORMAT commented out](https://user-images.githubusercontent.com/1630425/28885230-2164501e-7783-11e7-917c-d271fdd65dc8.png)

**Comment by cnieman** [comment] 2017-12-18 16:13
Is there any more information I can provide with respect to this issue?

**Comment by sdlime** [comment] 2017-12-21 22:14
I can replicate the issue but I need someone with better gdb skills than I have to actually find the offending code. @rouault, could I pick your brain on the best way to debug this?

**Comment by rouault** [comment] 2017-12-21 22:44
```
valgrind ./shp2img -m grid.map -o out.png
==23204== Memcheck, a memory error detector
==23204== Copyright (C) 2002-2015, and GNU GPL'd, by Julian Seward et al.
==23204== Using Valgrind-3.11.0 and LibVEX; rerun with -h for copyright info
==23204== Command: ./shp2img -m grid.map -o out.png
==23204== 
==23204== Conditional jump or move depends on uninitialised value(s)
==23204==    at 0x4C2EDA1: free (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==23204==    by 0x4F5CD8F: msFreeShape (mapprimitive.c:160)
==23204==    by 0x4EF1004: msGraticuleLayerNextShape (mapgraticule.c:302)
==23204==    by 0x4F69409: msLayerNextShape (maplayer.c:337)
==23204==    by 0x4F9D07B: msDrawVectorLayer (mapdraw.c:1094)
==23204==    by 0x4F9B92C: msDrawLayer (mapdraw.c:811)
==23204==    by 0x4F9A2CC: msDrawMap (mapdraw.c:388)
==23204==    by 0x40248B: main (shp2img.c:296)
==23204== 
```

I've just committed a fix. Appears it is indeed a regression due to changes I done in that area. I have added a test case that triggers this situation so we don't regress on that anymore

**Closed** 2017-12-21 22:43 UTC

**Comment by sdlime** [comment] 2017-12-22 16:34
Awesome, thanks!

**Comment by cnieman** [comment] 2017-12-22 16:35
Thanks!  I hoped to try this out today, but other things have gotten in the way.  I will definitely check on it when I'm back at work in the new year, though.
