### ISSUE TITLE
Build Error: called object ‘zend_error’ is not a function or function pointer

### ISSUE THREAD

**Issue by crankycyclops** [mapserver/mapserver#5319] opened 2016-09-02 22:06 UTC
Hi,

I'm trying to compile the PHP extension against PHP 5.6 and get the following error:

```
In file included from /usr/include/php/20131226/main/php.h:40:0,
                 from /usr/local/src/mapserver/mapscript/php/php_mapscript.h:35,
                 from /usr/local/src/mapserver/mapscript/php/error.c:32:
/usr/local/src/mapserver/mapscript/php/error.c: In function ‘zim_errorObj___get’:
/usr/include/php/20131226/Zend/zend_API.h:582:4: error: called object ‘zend_error’ is not a function or function pointer
    zend_error(E_ERROR, "String size overflow"); \
    ^
/usr/include/php/20131226/Zend/zend_API.h:626:39: note: in expansion of macro ‘ZVAL_STRING’
 #define RETVAL_STRING(s, duplicate)   ZVAL_STRING(return_value, s, duplicate)
                                       ^
/usr/local/src/mapserver/mapscript/php/php_mapscript_util.h:186:9: note: in expansion of macro ‘RETVAL_STRING’
         RETVAL_STRING( (value ? value:"") , 1);    \
         ^
/usr/local/src/mapserver/mapscript/php/error.c:71:8: note: in expansion of macro ‘IF_GET_STRING’
   else IF_GET_STRING("routine", php_error->error->routine)
        ^
In file included from /usr/local/src/mapserver/mapscript/php/php_mapscript.h:35:0,
                 from /usr/local/src/mapserver/mapscript/php/error.c:32:
/usr/include/php/20131226/main/php.h:293:19: note: declared here
 #define php_error zend_error
                   ^
/usr/local/src/mapserver/mapscript/php/error.c:58:21: note: in expansion of macro ‘php_error’
   php_error_object *php_error;
                     ^
In file included from /usr/include/php/20131226/main/php.h:40:0,
                 from /usr/local/src/mapserver/mapscript/php/php_mapscript.h:35,
                 from /usr/local/src/mapserver/mapscript/php/error.c:32:
/usr/include/php/20131226/Zend/zend_API.h:582:4: error: called object ‘zend_error’ is not a function or function pointer
    zend_error(E_ERROR, "String size overflow"); \
    ^
/usr/include/php/20131226/Zend/zend_API.h:626:39: note: in expansion of macro ‘ZVAL_STRING’
 #define RETVAL_STRING(s, duplicate)   ZVAL_STRING(return_value, s, duplicate)
                                       ^
/usr/local/src/mapserver/mapscript/php/php_mapscript_util.h:186:9: note: in expansion of macro ‘RETVAL_STRING’
         RETVAL_STRING( (value ? value:"") , 1);    \
         ^
/usr/local/src/mapserver/mapscript/php/error.c:72:10: note: in expansion of macro ‘IF_GET_STRING’
     else IF_GET_STRING("message", php_error->error->message)
          ^
In file included from /usr/local/src/mapserver/mapscript/php/php_mapscript.h:35:0,
                 from /usr/local/src/mapserver/mapscript/php/error.c:32:
/usr/include/php/20131226/main/php.h:293:19: note: declared here
 #define php_error zend_error
                   ^
/usr/local/src/mapserver/mapscript/php/error.c:58:21: note: in expansion of macro ‘php_error’
   php_error_object *php_error;
                     ^
/usr/local/src/mapserver/mapscript/php/error.c: In function ‘zim_errorObj___set’:
/usr/include/php/20131226/main/php.h:293:19: warning: variable ‘zend_error’ set but not used [-Wunused-but-set-variable]
 #define php_error zend_error
                   ^
/usr/local/src/mapserver/mapscript/php/error.c:85:21: note: in expansion of macro ‘php_error’
   php_error_object *php_error;
```

I've tried both the 7.0.1 release and the current code from git. Thanks!

**Comment by tbonfort** [comment] 2016-09-02 22:14
Duplicate of #5318

**Closed by tbonfort** 2016-09-02 22:14 UTC
