### ISSUE TITLE
Mapserver won't load shape files with a "." in their name

### ISSUE THREAD

**Issue by almaniac** [mapserver/mapserver#5898] opened 2019-10-16 14:38 UTC
For example, I was trying to use a shape file with this name:
TM_WORLD_BORDERS-0.3.shp

Mapserver would throw an error saying it was unable to load the file.  If I changed the name to:
TM_WORLD_BORDERS-03.shp

It worked.  I suspect the code is doing a simple string split on "." to determine the root file name, and coming up with "TM_WORLD_BORDERS-0", which then doesn't exist in the file system.

If that's what's going on it could be simply fixed by ensuring the array returned by split had a length of 2, and then rebuilding the file name part if it was longer.

**Comment by almaniac** [comment] 2019-10-16 14:39
Forgot to say, I'm using the MS4W version 4.0.1 distribution.

**Comment by jratike80** [comment] 2019-10-16 16:02
Strictly speaking filename with a dot is invalid by the shapefile specification https://www.esri.com/library/whitepapers/pdfs/shapefile.pdf

> All file names adhere to the 8.3 naming convention.  The main file, the index file, and the
> dBASE file have the same prefix.  The prefix must start with an alphanumeric character
> (a–Z, 0–9), followed by zero or up to seven characters (a–Z, 0–9, _, -).  The suffix for
> the main file is .shp.  The suffix for the index file is .shx.  The suffix for the dBASE table
> is .dbf.  All letters in a file name are in lower case on operating systems with case
> sensitive file names

I know that ESRI itself has relaxed the naming rules and allows for example longer names but I do not know if it accepts extra dots in the names.

**Comment by almaniac** [comment] 2019-10-16 17:04
Interesting.  Still, perhaps a warning could be generated in that case, or the error message could be more specific.  

I'll also flag this as an issue with the supplier of the file.

**Comment by jmckenna** [comment] 2019-10-19 18:49
For the record, I just tested and verified that MS4W version 4.0.1 is able to generate map images, with shapefiles in format name.name.shp    (I of course had to put the filename in double-quotes in the DATA statement inside the mapfile)

Closing ticket.

If you have any questions like this for the MS4W community, join the MS4W forum at: https://ms4w.com/forum/

**Closed by jmckenna** 2019-10-19 18:49 UTC

**Comment by jratike80** [comment] 2019-10-21 18:59
Seems to be more or less a duplicate of #2895.
