### ISSUE TITLE
WCS: Origin of rectifiedGrid

### ISSUE THREAD

**Issue by ajolma** [mapserver/mapserver#5511] opened 2017-11-07 11:34 UTC
The origin of the rectifiedGrid is written (mapwcs.c:1193) as geotransform[0] and [3], which is extent boundaries. The origin should be expressed as the center of the grid point.

**Comment by rouault** [comment] 2017-11-08 12:42
mapwcs.c is about WCS 1.0 and whole GDAL & MapServer code use pixel-corner convention, so I don't think things should be changed there
mapwcs11.c applies a half pixel shift for GridOrigin per https://github.com/mapserver/mapserver/blob/branch-7-0/mapwcs11.c#L724
So it looks the issue is for WCS 2.0 where this half pixel shift is not applied, but it should. @Schpidi any opinion ?

**Comment by ajolma** [comment] 2017-11-08 12:47
Yes, sorry, I was too quick to point to the place in code. I saw the error in XML returned by a server when testing the new GDAL WCS driver.

**Comment by rouault** [comment] 2017-11-09 11:15
Fix committed per 31c25df6be067a59ffb89100f215d2d65840e364
Both GeoServer and Rasdaman also use the center of grid point convention, so this fix was needed.

**Closed** 2017-11-09 11:14 UTC

**Comment by Schpidi** [comment] 2017-11-10 10:46
@rouault I fully agree with the necessary changes, many thanks for taking care!

**Comment by ajolma** [comment] 2017-11-18 13:33
I think this issue is also valid for 1.0.0. See for example http://194.66.252.155/cgi-bin/BGS_EMODnet_bathymetry/ows?SERVICE=WCS&REQUEST=DescribeCoverage&VERSION=1.0.0&COVERAGE=BGS_EMODNET_CentralMed-MCol 
In 1.0.0 the origin is at the center of pixel in ArcGIS and GeoServer
