### ISSUE TITLE
Mapserver hangs if the text is empty

### ISSUE THREAD

**Issue by krzbor** [mapserver/mapserver#5167] opened 2015-09-19 21:37 UTC
Mapserver (7.0.0) hangs if the text is empty:
LAYER
	#NAME         je_100_n
	GROUP         granice
	METADATA
	  "wms_title"    "Powiaty - nazwy"   ##required‚‚
	END
	PROJECTION
		"init=epsg:2180"   ##required
	END

	DATA         je100O
	STATUS       off
	TYPE         polygon
	LABELITEM    "NAZWA" #  <--------- hangs if the text is empty
	CLASS
		LABEL
			ENCODING WINDOWS-1250
			FORCE TRUE
			COLOR 200 0 0
			TYPE TRUETYPE
			FONT arial
			SIZE 9
			ANTIALIAS FALSE
			POSITION cc
			PARTIALS FALSE
			STYLE
				GEOMTRANSFORM 'labelpoly'
				COLOR 255 255 255
			END
		END # end of label
	END
END

**Comment by tbonfort** [comment] 2015-09-21 08:10
unable to reproduce with a simple testcase. please provide a full testcase (data + full mapfile + request)

**Comment by krzbor** [comment] 2015-09-21 20:28
It is difficult for me to extract a small piece of data and file maps. The server hangs when I try to view the area where the attribute value is empty. I changed a blank text on the minus sign (inside DBF file) and everything was OK.

**Comment by mkofahl** [comment] 2015-09-21 20:48
@krzbor Are you able to compile branch-7-0 with patch 5570f5d3c960ab109bc5574fb9de028eb3624609 yourself? I noticed the same behaviour (infinitve loop until http server timeout) when labelitem met database null-values. A simplified test-case worked however. I found a small typo in `msAddLabelGroup` which solved the problem for mee.

**Comment by krzbor** [comment] 2015-09-23 18:54
5570f5d patch solved my problem. Thank you mkofahl

**Comment by ejn** [comment] 2015-10-12 14:43
Merged #5169 fixes this according to OP. Closing.

**Closed by ejn** 2015-10-12 14:43 UTC
