### ISSUE TITLE
PHP mapscript 7.0.0 ms_newGridObj appears non-functional

### ISSUE THREAD

**Issue by dshorthouse** [mapserver/mapserver#5159] opened 2015-09-06 21:55 UTC
I upgraded to 7.0.0 from 6.4.2 and I cannot get ms_newGridObj to work in PHP mapscript, which was working just fine. No errors are thrown with the same code - just no GRID no matter what I attempt. When I use shp2img using a barebones map file however, GRID does work.

**Comment by dshorthouse** [comment] 2015-09-21 13:45
Can anyone verify this?

**Comment by dshorthouse** [comment] 2015-09-22 18:01
I had a suspicion that the GRID block was not being created with ms_newGridObj. If it's any indication, saving out the map object to a mapfile sure enough shows the complete absence of the GRID block. As a workaround, I'm temporarily using updateFromString to programmatically inject the GRID block.

**Comment by tbonfort** [comment] 2015-09-23 07:19
please provide a minimal php script that exhibits the behavior

**Comment by dshorthouse** [comment] 2015-09-23 13:52
<?php

    $mapfile_string = "
        MAP
            OUTPUTFORMAT
                NAME png
                DRIVER AGG/PNG
                IMAGEMODE RGB
                MIMETYPE 'image/png'
                EXTENSION 'png'
            END
        END";

    $projection = 'proj=longlat,ellps=WGS84,datum=WGS84,no_defs';

    # MAP Object
    $map_obj = ms_newMapObjFromString($mapfile_string);
    $map_obj->setProjection($projection);
    $map_obj->set("name", "grid_test");
    $map_obj->web->set("template", "template.html");
    $map_obj->set("units", MS_DD);
    $map_obj->selectOutputFormat("png");
    $map_obj->setExtent(-180, -90, 180, 90);
    $map_obj->setSize(600,200);

    # GRID Layer
    $layer = ms_newLayerObj($map_obj);
    $layer->set("name", "grid");
    $layer->set("type", MS_LAYER_LINE);
    $layer->set("status", MS_ON);
    $layer->setProjection($projection);

    $class = ms_newClassObj($layer);
    $style = ms_newStyleObj($class);
    $style->color->setRGB(200, 200, 200);

    /* GRID ... END IS NOT CREATED in 7.0.0 */
    ms_newGridObj($layer);
    $layer->grid->set("labelformat", "DDMMSS");

    /* ALTERNATE GRID CREATION FROM STRING
    $grid_string  = 'LAYER name "grid"' . "\n";
    $grid_string .= 'GRID' . "\n";
    $grid_string .= 'labelformat "DDMMSS"' . "\n";
    $grid_string .= 'END' . "\n";
    $grid_string .= 'END' . "\n";
    $layer->updateFromString($grid_string);
    */

    # OUTPUT
    header("Content-Type: image/png");
    $image = $map_obj->drawQuery();
    $image->saveImage("");

    /* ALTERNATE OUTPUT TO MAPFILE
    $map_obj->save("/tmp/mapfile.map");
    */

**Comment by tbonfort** [comment] 2015-09-29 11:24
Caused by the changes in #4913 . Assigning to @szekerest

**Comment by szekerest** [comment] 2015-10-02 18:25
Could someone check is the commit above is working? 
I have no chance to test php at the moment.

**Comment by jmckenna** [comment] 2015-10-29 17:12
Checking....

**Comment by jmckenna** [comment] 2015-10-29 19:24
i get the same issue with master, on windows, with that test script (GRID object is not written to the mapfile).

**Comment by tbonfort** [comment] 2015-10-29 19:30
@szekerest posted a proposed fix in his clone in 57f9ecb but nobody tried it out. it has not been merged into master or branch-7-0 as it hasn't been tested.

**Comment by jmckenna** [comment] 2015-10-29 19:47
good lord i just spent 2 hours getting master to work here.   umm....can you apply this to master so it is easier to test?

**Comment by tbonfort** [comment] 2015-10-29 20:02
not applying to master before someone actually confirms it fixes the issue given tamas couldn't test.

```
git remote add szekerest https://github.com/szekerest/mapserver.git
git fetch szekerest
git checkout 57f9ecb
=>build and test!
```

**Comment by jmckenna** [comment] 2015-10-29 20:05
for windows i have to make many custom changes, for my builds to work (especially for the mapscripts).  It is hard to explain.

**Comment by tbonfort** [comment] 2015-10-29 20:14
then let @dshorthouse test the fix. this isn't windows specific.

**Comment by jmckenna** [comment] 2015-10-29 22:40
I confirm this fix (manually, with files from @szekerest 's clone).  The resulting map image contains grid lines.  The resulting map layer does contain a GRID object:
```
  LAYER
    NAME "grid"
    PROJECTION
      "proj=longlat"
      "ellps=WGS84"
      "datum=WGS84"
      "no_defs"
    END # PROJECTION
    STATUS ON
    TILEITEM "location"
    TYPE LINE
    UNITS METERS
    CLASS
      STYLE
        COLOR 200 200 200
      END # STYLE
    END # CLASS
    GRID
      LABELFORMAT "%3d %02d %02d"
      MAXSUBDIVIDE 256
      MINSUBDIVIDE 256
    END # GRID
  END # LAYER
```

**Comment by dshorthouse** [comment] 2015-10-30 02:58
Thanks @jmckenna for confirming the fix. Apologies for not being able to do it myself. I'll let others close the fix once it's pulled into master.

**Comment by tbonfort** [comment] 2015-10-30 06:59
applied to branch-7-0 in 4dacec0e25

**Closed** 2016-01-04 10:17 UTC
