### ISSUE TITLE
DATA filenames with umlauts & relative path don't work, on Windows

### ISSUE THREAD

**Issue by treenok** [mapserver/mapserver#5995] opened 2020-02-21 08:19 UTC
I figured out problems with raster filenames containing umlauts.

To reproduce it, just call

shp2img -m mypath/umlauttest.map -o myImg.png

I tracked it down to the function msTryBuildPath3 and the fopen call with UTF-8 chars.
Every fopen call with  UTF-8 chars ( 2 or more bytes) will fail on windows.
That seems to be a general problem, not only with rasters.
The gdal source handles this in another way, e.g. 

VSIWin32FilesystemHandler::Open
...
 if( CPLTestBool(CPLGetConfigOption( "GDAL_FILENAME_IS_UTF8", "YES" ) ) )
    {
        wchar_t *pwszFilename =
            CPLRecodeToWChar( pszFilename, CPL_ENC_UTF8, CPL_ENC_UCS2 );

        hFile = CreateFileW( pwszFilename, dwDesiredAccess,
                            bShared ? FILE_SHARE_READ | FILE_SHARE_WRITE : 0,
                            nullptr, dwCreationDisposition,  dwFlagsAndAttributes,
                            nullptr );
   ...

[umlauttest.zip](https://github.com/mapserver/mapserver/files/4234943/umlauttest.zip)

**Comment by jmckenna** [comment] 2020-02-21 15:59
@treenok thank you for providing a simple test case (!).    Unfortunately I cannot reproduce, on Windows with MS4W 4.0.3  (I get a nice blue map image)    I notice that you are using MS4W, what version do you have?      I also tried with git-master and no issues.

**Comment by treenok** [comment] 2020-02-21 18:37
I use a ms4w based version with self compiled mapserver( 4.02) and gdal ( 2.43).

Did you try it with a relative path to the mapfile ( -m mypath/umlauttest.map)?

First time the problem occured  in a wms service.  
That's why I tested it with shp2img.
If I start shp2img in the current directory of the mapfile, it works!

Gdal expects the path to be in UTF-8 notation and it gets only the relative filename  ( because  msTryBuildPath3 fails). 
But the relative path fails  when the process has a different working directory!
I think, mapserver is mixing UTF-8 path components ( e.g. DATA from mapfile) with otherwise encoded path components ( map->mappath ).
I'm gonna test the official ms4w binaries twomorrow...

**Comment by jmckenna** [comment] 2020-02-21 18:47
I just now also tried with a relative path to the mapfile, no issues here.

**Comment by jmckenna** [comment] 2020-02-21 18:49
my exact command is:
```
shp2img -m folder/umlauttest.map -o myImg.png
```

**Comment by jmckenna** [comment] 2020-02-21 19:55
I believe the problem is that this is a non-georeferenced tif file.  You are missing a 'world file' with this (https://gdal.org/drivers/raster/wld.html).  Meaning that it will work with shp2img, but MapServer (and clients such as QGIS) will have trouble reprojecting the data through WMS services (resulting in blank images returned).

**Comment by jmckenna** [comment] 2020-02-21 23:16
wow @treenok  did you ever discover a good bug!!!!?!!!  But I had to not use your test tif, as it seemed to have no georeferencing.  It has nothing to do with relative or absolute, but just the filename.  See below:

# Confirmed Issue with umlaut in raster filename

I confirm that raster filenames with umlaut work at commandline, but through WMS produce a blank image, and the MS_ERRORFILE mentions "corrupt file 'ä1-jeff.tif' ignoring data..."

# Test Archive

I have created a new test archive, that contains a 'commands.txt' as well.  
[ticket-5995-umlauts.zip](https://github.com/mapserver/mapserver/files/4238367/ticket-5995-umlauts.zip)

It contains 2 small GeoTIFF files, exact copies of each other, except the filename, as well as a WMS-server mapfile, and commands.txt :
```
ä1-jeff.tif
jeff.tif
umlauttest.map
commands.txt
```

# Working Demo urls to try

## WMS request using data "ä1-jeff.tif" 
https://ms4w.dev/cgi-bin/mapserv.exe?map=%5Cms4w%5Capps%5Cticket-5995-umlauts%5Cumlauttest.map&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=44.31779999999999831,-64.29529999999999745,44.39609999999999701,-64.19759999999999422&CRS=EPSG:4326&WIDTH=410&HEIGHT=329&LAYERS=with-umlaut-in-data-filename&STYLES=&FORMAT=image/png&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96&TRANSPARENT=TRUE

## WMS request using data "jeff.tif" 
https://ms4w.dev/cgi-bin/mapserv.exe?map=%5Cms4w%5Capps%5Cticket-5995-umlauts%5Cumlauttest.map&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=44.31779999999999831,-64.29529999999999745,44.39609999999999701,-64.19759999999999422&CRS=EPSG:4326&WIDTH=410&HEIGHT=329&LAYERS=without-umlaut-in-data-filename&STYLES=&FORMAT=image/png&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96&TRANSPARENT=TRUE

# commands.txt contents

```
# with umlaut in filename <--works at commandline!!
shp2img -m umlauttest.map -l with-umlaut-in-data-filename -o with-umlaut.png -all_debug 5

# without umlaut in filename
shp2img -m umlauttest.map -l without-umlaut-in-data-filename -o without-umlaut.png -all_debug 5

# commandline WMS GetMap, with umlaut in filename <--works at commandline!!
mapserv -nh QUERY_STRING="map=\ms4w\apps\ticket-5995-umlauts\umlauttest.map&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=44.31779999999999831,-64.29529999999999745,44.39609999999999701,-64.19759999999999422&CRS=EPSG:4326&WIDTH=410&HEIGHT=329&LAYERS=with-umlaut-in-data-filename&STYLES=&FORMAT=image/png&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96&TRANSPARENT=TRUE" > with-umlaut.png

# commandline WMS GetMap, without umlaut in filename
mapserv -nh QUERY_STRING="map=\ms4w\apps\ticket-5995-umlauts\umlauttest.map&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=44.31779999999999831,-64.29529999999999745,44.39609999999999701,-64.19759999999999422&CRS=EPSG:4326&WIDTH=410&HEIGHT=329&LAYERS=without-umlaut-in-data-filename&STYLES=&FORMAT=image/png&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96&TRANSPARENT=TRUE" > without-umlaut.png

# WMS GetMap, with umlaut in filename <--returns blank image
https://ms4w.dev/cgi-bin/mapserv.exe?map=%5Cms4w%5Capps%5Cticket-5995-umlauts%5Cumlauttest.map&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=44.31779999999999831,-64.29529999999999745,44.39609999999999701,-64.19759999999999422&CRS=EPSG:4326&WIDTH=410&HEIGHT=329&LAYERS=with-umlaut-in-data-filename&STYLES=&FORMAT=image/png&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96&TRANSPARENT=TRUE

   MS_ERRORFILE :
   
		[Fri Feb 21 18:46:40 2020].787000 CGI Request 1 on process 4492
		[Fri Feb 21 18:46:40 2020].791000 msDrawMap(): rendering using outputformat named png (AGG/PNG).
		[Fri Feb 21 18:46:40 2020].791000 msDrawMap(): WMS/WFS set-up and query, 0.000s
		[Fri Feb 21 18:46:40 2020].792000 msDrawRasterLayerLow(with-umlaut-in-data-filename): entering.
		[Fri Feb 21 18:46:40 2020].865000 Corrupt, empty or missing file 'ä1-jeff.tif' for layer 'with-umlaut-in-data-filename' ... ignoring this missing data.  
		[Fri Feb 21 18:46:40 2020].865000 msDrawMap(): Layer 0 (with-umlaut-in-data-filename), 0.074s
		[Fri Feb 21 18:46:40 2020].866000 msDrawMap(): Drawing Label Cache, 0.000s
		[Fri Feb 21 18:46:40 2020].866000 msDrawMap() total time: 0.075s
		[Fri Feb 21 18:46:40 2020].871000 msSaveImage(stdout) total time: 0.005s
		[Fri Feb 21 18:46:40 2020].871000 mapserv request processing time (msLoadMap not incl.): 0.084s
		[Fri Feb 21 18:46:40 2020].871000 msFreeMap(): freeing map at 0095D0C8.
		[Fri Feb 21 18:46:40 2020].871000 freeLayer(): freeing layer at 00965490.
		[Fri Feb 21 18:46:40 2020].871000 freeLayer(): freeing layer at 00966038.
		
# WMS GetMap, without umlaut in filename
https://ms4w.dev/cgi-bin/mapserv.exe?map=%5Cms4w%5Capps%5Cticket-5995-umlauts%5Cumlauttest.map&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=44.31779999999999831,-64.29529999999999745,44.39609999999999701,-64.19759999999999422&CRS=EPSG:4326&WIDTH=410&HEIGHT=329&LAYERS=without-umlaut-in-data-filename&STYLES=&FORMAT=image/png&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96&TRANSPARENT=TRUE

   MS_ERRORFILE :
   
		[Fri Feb 21 18:49:30 2020].970000 CGI Request 1 on process 3108
		[Fri Feb 21 18:49:30 2020].973000 msDrawMap(): rendering using outputformat named png (AGG/PNG).
		[Fri Feb 21 18:49:30 2020].973000 msDrawMap(): WMS/WFS set-up and query, 0.000s
		[Fri Feb 21 18:49:30 2020].975000 msDrawRasterLayerLow(without-umlaut-in-data-filename): entering.
		[Fri Feb 21 18:49:30 2020].979000 msResampleGDALToMap in effect: cellsize = 20.000000
		[Fri Feb 21 18:49:30 2020].980000 msDrawGDAL(without-umlaut-in-data-filename): using RAW_WINDOW=0 0 544 609, dst=0,0,544,609
		[Fri Feb 21 18:49:30 2020].980000 msDrawRasterLayerGDAL(): red,green,blue,alpha bands = 1,2,3,0
		[Fri Feb 21 18:49:30 2020].986000 msDrawMap(): Layer 1 (without-umlaut-in-data-filename), 0.013s
		[Fri Feb 21 18:49:30 2020].986000 msDrawMap(): Drawing Label Cache, 0.000s
		[Fri Feb 21 18:49:30 2020].986000 msDrawMap() total time: 0.013s
		[Fri Feb 21 18:49:31 2020].0 msSaveImage(stdout) total time: 0.014s
		[Fri Feb 21 18:49:31 2020].0 mapserv request processing time (msLoadMap not incl.): 0.030s
		[Fri Feb 21 18:49:31 2020].0 msFreeMap(): freeing map at 0136CFD8.
		[Fri Feb 21 18:49:31 2020].0 freeLayer(): freeing layer at 01375298.
		[Fri Feb 21 18:49:31 2020].0 freeLayer(): freeing layer at 01375E40.		

```
# WMS mapfile contents
```
MAP
  NAME "umtest"
  STATUS ON
  EXTENT -7157323.156 5514762.172 -7146443.156 5526942.172
  SIZE 500 500
  IMAGETYPE png
  IMAGECOLOR 255 255 255
  UNITS METERS
  SHAPEPATH "./"
  CONFIG "MS_ERRORFILE" "/ms4w/tmp/ms_error.txt"
  DEBUG 5
  WEB
    IMAGEPATH "/ms4w/tmp/ms_tmp" 
    METADATA
      "wms_title"   			"MS4W Demo WMS Server"
      "wms_abstract"      		"This demonstration server was setup by Gateway Geomatics (https://gatewaygeomatics.com/) and is powered by MS4W (https://ms4w.com/)."      
      "wms_onlineresource" 	"https://ms4w.dev/cgi-bin/mapserv.exe?map=\ms4w\apps\ticket-5995-umlauts\umlauttest.map"
      "wms_service_onlineresource" "https://gatewaygeomatics.com/"    
      "wms_contactperson"		"Jeff McKenna" 
      "wms_contactorganization" "Gateway Geomatics"
      "wms_contactposition"		"President"
      "wms_contactelectronicmailaddress" "info@gatewaygeomatics.com"
      "wms_srs"   				"EPSG:3857 EPSG:31467 EPSG:4326 EPSG:4269"
      "wms_getfeatureinfo_formatlist" "text/plain,text/html,application/json,application/vnd.ogc.gml,gml"
      "wms_enable_request" 	"*"
    END #metadata
  END #web
  
  PROJECTION  
    "init=epsg:3857"
  END #projection
  
  OUTPUTFORMAT
    NAME "png"
    DRIVER AGG/PNG
    MIMETYPE "image/png"
    IMAGEMODE RGB
    EXTENSION "png"
    FORMATOPTION "GAMMA=0.75"
  END 

  LAYER
    NAME "with-umlaut-in-data-filename"
    TYPE RASTER
	STATUS ON	
    METADATA
      "wms_title" 			"with-umlaut-in-data-filename"
      "wms_include_items" 	        "all"
	  "wms_srs" 			"EPSG:3857"
    END #metadata
	EXTENT -7157323.156 5514762.172 -7146443.156 5526942.172
    DATA  "ä1-jeff.tif"
    CLASS
      NAME "with-umlaut-in-data-filename"
    END	
    PROJECTION
      "init=epsg:3857"
    END #projection
	DEBUG 5
  END #layer
  
    LAYER
    NAME "without-umlaut-in-data-filename"
    TYPE RASTER
	STATUS ON	
    METADATA
      "wms_title" 			"without-umlaut-in-data-filename"
      "wms_include_items" 	        "all"
	  "wms_srs" 			"EPSG:3857"
    END #metadata
	EXTENT -7157323.156 5514762.172 -7146443.156 5526942.172
    DATA  "jeff.tif"
    CLASS
      NAME "without-umlaut-in-data-filename"
    END	
    PROJECTION
      "init=epsg:3857"
    END #projection
	DEBUG 5
  END #layer
  
END #mapfile
```
# Thoughts
I hope this helps others to confirm (or deny!) locally.

**Comment by jmckenna** [comment] 2020-02-21 23:43
Confirmed the same issue occurs on Ubuntu, with master from today's source, actually on Linux it returns the error "Corrupt, empty or missing file 'ä1-jeff.tif'"   in the response: 

https://demo.gatewaygeomatics.com/cgi-bin/mapserv?map=/home/apps/ticket-5995-umlauts/umlauttest.map&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=44.31779999999999831,-64.29529999999999745,44.39609999999999701,-64.19759999999999422&CRS=EPSG:4326&WIDTH=410&HEIGHT=329&LAYERS=with-umlaut-in-data-filename&STYLES=&FORMAT=image/png&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96&TRANSPARENT=TRUE

**Comment by treenok** [comment] 2020-02-22 08:25
Thank you Jeff, but I guess it depends on relative path.
Could you please include an additional layer with umlaut and full path ( DATA "/abs/olute/path/to/ä1-jeff.tif")?
So GDAL will see the complete UTF-8 path and will open the image without errors.

**Comment by jmckenna** [comment] 2020-02-22 14:17
@treenok I updated 
[ticket-5995-umlauts.zip](https://github.com/mapserver/mapserver/files/4239441/ticket-5995-umlauts.zip)
 (and live demos) with a new layer with umlauts and full path to data; oddly it works on Windows (like above), but fails on Linux:

path specified in mapfile: /home/apps/ticket-5995-umlauts/ä1-jeff.tif

https://demo.gatewaygeomatics.com/cgi-bin/mapserv?map=/home/apps/ticket-5995-umlauts/umlauttest.map&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=44.31779999999999831,-64.29529999999999745,44.39609999999999701,-64.19759999999999422&CRS=EPSG:4326&WIDTH=410&HEIGHT=329&LAYERS=with-umlaut-in-data-filename-absolute-path&STYLES=&FORMAT=image/png&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96&TRANSPARENT=TRUE

I will hold the 7.6.0 release for this issue, as I believe it could be a nice improvement.  @treenok are you able to submit a Pull Request with the changes that you initially mentioned here?  (thank you again for finding this!)

**Comment by treenok** [comment] 2020-02-22 19:34
@jmckenna , sorry, I know too little about it. Think it needs a general revision  of the file system access. There are probably other areas with problematic mixtures of different encoded path components ( tileindex e.g.). I don't see an easy solution. 
Of course you could redirect fopen calls, but that's not enough, especially when the working directory contains umlauts.

**Comment by treenok** [comment] 2020-02-24 07:19
One more small addition, here (Win 10, ms4w 4.03) it's enough to run shp2img outside the mapfile directory. @jmckenna , sure there is no copy of ä1-jeff.tif in your command working directory?

**Comment by jmckenna** [comment] 2020-02-24 13:55
@treenok here are my steps:
 - extract test case into /ms4w/apps/
 - open command window
 - cd ms4w
 - setenv.bat
 - shp2img -m apps\ticket-5995-umlauts\umlauttest.map -o ttt.png -map_debug 3

a valid ttt.png image is generated in the folder \ms4w\apps\ticket-5995-umlauts\

**Comment by jmckenna** [comment] 2020-02-24 14:01
Ah, the message was hidden in the MS_ERRORFILE.  I confirm what you said @treenok , here was my exact command that throws an error:

```
shp2img -m apps\ticket-5995-umlauts\umlauttest.map -l with-umlaut-in-data-filename -o ttt.png -map_debug 3
```
Response:
```
msDrawMap(): rendering using outputformat named png (AGG/PNG).
msDrawMap(): WMS/WFS set-up and query, 0.000s
msDrawRasterLayerLow(with-umlaut-in-data-filename): entering.
Corrupt, empty or missing file '├ñ1-jeff.tif' for layer 'with-umlaut-in-data-filename' ... ignoring this missing data.
msDrawMap(): Layer 0 (with-umlaut-in-data-filename), 0.006s
msDrawMap(): Drawing Label Cache, 0.000s
msDrawMap() total time: 0.009s
msSaveImage(ttt.png) total time: 0.006s
freeLayer(): freeing layer at 00ECFE98.
freeLayer(): freeing layer at 00ED7880.
freeLayer(): freeing layer at 00ED8630.
```
And you are correct, if I run the same command inside the same folder as the mapfile, no error (!?).

**Comment by jmckenna** [comment] 2020-02-24 14:08
Confirmed also on Linux with today's master.   @sdlime can you take a look at this issue?

**Comment by jratike80** [comment] 2020-02-24 14:32
I repeated Jeff's test with the same result: error when running the command from c:\ms4w, no error when running from C:\ms4w\apps\ticket-5995-umlauts.

As coming from another umlaut country I try to avoid using äöå in GIS filenames and paths but sometimes it is not so easy, especially when playing with data that comes outside our house.

**Comment by sdlime** [comment] 2020-02-25 18:12
Is this issue limited to just raster files or does a shapefile also suffer from the same problem?

**Comment by jmckenna** [comment] 2020-02-25 18:52
Also fails with shapefiles. "msShapefileOpen(): Unable to access file"

see error: https://ms4w.dev/cgi-bin/mapserv.exe?map=%5Cms4w%5Capps%5Cticket-5995-umlauts%5Cumlauttest.map&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=44.31779999999999831,-64.29529999999999745,44.39609999999999701,-64.19759999999999422&CRS=EPSG:4326&WIDTH=410&HEIGHT=329&LAYERS=shapefile-with-umlaut-in-data-filename&STYLES=&FORMAT=image/png&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96&TRANSPARENT=TRUE

**Comment by jmckenna** [comment] 2020-02-25 19:00
Updated test archive, added shapefile and layer. 
[ticket-5995-umlauts.zip](https://github.com/mapserver/mapserver/files/4251646/ticket-5995-umlauts.zip)

exact command that throws error with shapefile:
```
shp2img -m umlauttest.map -l shapefile-with-umlaut-in-data-filename -o with-umlaut.png -all_debug 5
```

**Comment by sdlime** [comment] 2020-02-25 19:59
This also isn't limited to WMS... Are relative paths even part of the issue?

**Comment by jmckenna** [comment] 2020-02-25 20:05
Agreed about not only WMS.    Absolute path in DATA statement with umlaut has mixed results, works through Windows but fails on Linux.

**Comment by jmckenna** [comment] 2020-02-25 20:09
(relative paths with umlaut fails on both Linux and Windows)

The relative/absolute differences confuse me as well.

**Comment by sdlime** [comment] 2020-02-25 20:47
In Linux (SLES 15.1) with MapServer 7.4 I'm unable to recreate the issue. Jeff, when I unzipped your test case all of the filenames with umlauts were munged (e.g. ?1-jeff.tif). However, inside the mapfile the umlaut characters where intact. So, I had to rename the files using the names in the mapfile and everything worked as expected (I see the umlauts in the filenames when doing a directory listing). 

Same issue with the original test case from @treenok... 

Seems like umlaut character in the mapfile and filename are not the same and hence the error?

**Comment by jmckenna** [comment] 2020-02-25 21:22
Yikes you are correct, every time I zip the files through 7zip on Windows then transfer to Linux, and extract, the umlaut files are munged.  (but if I transfer directly, without 7zip the files are ok and work on Linux as-is).

I'm not sure what is happening on Windows, as I copy the filename from the mapfile and rename the file, same error.

Need to think on this more I guess. Darn.  Thanks for solving the Linux side Steve.

**Comment by jmckenna** [comment] 2020-02-25 21:30
tar archive works fine though, darn sorry for using zip.  Never again.

**Comment by treenok** [comment] 2020-02-26 07:48
I guess symbol filenames will also affected under windows, maybe include files too. 
Every filename with umlauts specified in the mapfile and directly proccessed by mapserver will fail, no matter if relative or absolute.

There will be no problems on systems with UTF-8 as standard locale(like linux), but on windows the default locale(codepage) is usually not  UTF-8. So system calls like "getcwd,fopen,etc" returns/expects the path to be encoded in the current codepage.
 
GDAL expects filenames to be encoded with UTF-8, so feeding the API with UTF-8 filenames works. 
Mapserver always try to build a absolute path before it calls the GDAL-API. If this fails (path is already absolute or mixed encoded path components), GDAl see the original string from DATA filename.
Thats why absolute paths works.  Relative paths works only, if these filenames are valid to the current working directory ( and not, as expected relative to the mapfile path).

**Comment by jmckenna** [comment] 2020-02-26 12:25
@treenok you seem to be right, because if I try to view an umlaut file through CONNECTIONTYPE OGR it works perfectly on Windows in MapServer, such as:
```
        CONNECTIONTYPE OGR
	CONNECTION "ä1.shp"
```

**Comment by jmckenna** [comment] 2020-04-05 15:45
Reopened just for others to confirm this.  I've tested @rouault's fix for this through #6037 and confirmed on Windows (my tests with umlauts in filename that failed earlier, now pass when testing master).   Please others test here, to confirm the fix, so we can close this ticket.

**Comment by jmckenna** [comment] 2020-04-10 15:06
closing.  Please re-open this ticket if your testing of the committed changes show additional problems.

**Comment by szekerest** [comment] 2020-04-13 18:34
I encounter the same issue in branch-7-6, which is very annoying because we cannot open a mapfile or a shape layer having special characters in the filenames. As of mapserver 7.0 all filenames are declared to be considered as UTF-8, but many of the file open calls haven't been updated to work with UTF-8 on Windows. This fix is a good candidate to be backported to the 7-6 branch and make things to work again.

**Comment by jmckenna** [comment] 2020-04-13 20:05
Correct that the fix was only applied to master, because in the pull request #6037 @rouault stated "Likely not appropriate for backport", so I assumed this meant that the fix cannot be applied to branch7-6   @szekerest what do you suggest?  I personally fully agree that this fix is critical for the 7.6.0 release.

**Comment by jmckenna** [comment] 2020-04-13 20:07
@szekerest you state that "this fix is a good candidate to be backported to the 7-6 branch" but @rouault said that the fix cannot be applied.    
Ok, I will now try to backport to branch-7-6.   Sorry, I was following @rouault's words.   Working on this now...

**Comment by rouault** [comment] 2020-04-13 20:30
I didn't feel the backport was really an obvious good idea, as the changes slightly alter the API/ABI of mapshape.h (changing members of structures from plain FILE* to GDAL VSIFILE*) and I wasn't sure if outside users might rely on that. I don't think so, as those structures should be considered mostly opaque for users, so that's probably low risk. Another annoyance is that there's sometimes a compilation error on Linux with including "cpl_vsi.h" from C files (an issue I already got in GDAL itself in the past), which obliges to convert some files to C++.

**Comment by jmckenna** [comment] 2020-04-13 20:42
Ok thanks for the detailed explanation @rouault, 

My opinion is to include in branch-7-6/release 7.6.0.  I feel the same as @szekerest that this is too important a fix to live without, and affects too many users.  I feel a 'sometimes' Linux error versus a 100% show-stopper for Windows users with special characters in filenames warrants the inclusion in 7.6.0 release.  Of course I could be (and often am) totally wrong, but that's my gut feeling here.

I will proceed with the backport.

**Comment by jmckenna** [comment] 2020-04-13 22:25
applied to branch-7-6 through 82750e4  Verified with umlaut in filename on Windows.  Closing ticket, please re-open if any issues in your testing.

**Closed by jmckenna** 2020-04-13 22:25 UTC
Labels: Bug, Feedback requested

**Comment by treenok** [comment] 2020-04-14 08:00
Nice to see that mapserver are now using GDAL file API, this fixes a lot of problems. But probably not all. There are still places where UTF-8 and non UTF-8 are mixed.
I guess, if the mapfile is located in a directory that contains umlauts, we will see the problems.
Think, the "getcwd" calls in mapfile.c  need a review.

**Comment by jmckenna** [comment] 2020-04-14 11:25
@treenok my directory is named "ticket-5995-umlauts-ä1" and no issues with the following command:
```
shp2img -m apps\ticket-5995-umlauts-ä1\umlauttest.map -l with-umlaut-in-data-filename -o ttt.png -map_debug 3
```

**Comment by jmckenna** [comment] 2020-04-14 11:27
@treenok second test is from inside the "ticket-5995-umlauts-ä1" directory, no issues.

**Comment by szekerest** [comment] 2020-04-14 15:53
Great, thank you @jmckenna

**Comment by szekerest** [comment] 2020-04-14 17:15
@jmckenna I think this issue also applied to msLoadMap/msSaveMap which should also be fixed. Though it might be a subject of another bug.
