### ISSUE TITLE
crash creating pdf output with cairo

### ISSUE THREAD

**Issue by worthlutz** [mapserver/mapserver#5273] opened 2016-04-21 15:12 UTC
I'm seeing a crash, "Aborted (core dumped)" at the end of a cli run of mapscript creating some PDF maps. 

I believe this same error happens when calling the same code through the web server.  That error is shown in the attached screenshot from the server.

My php script has completed it's work and the error occurs during the exit of the program.  I think during cleanup.

Google found me these two links which I think describe the same problem in Mapnik.

https://github.com/mapnik/mapnik/issues/3323

https://github.com/mapnik/mapnik/issues/3304

I have determined that the problem is related to drawing a layer which is putting on labels.  I removed the Hwy symbols and just left the text and still see the problem.  Remove the text and the problem goes away.

I'm running mapServer v6.4.2 on Ubuntu 14.04.

Attached is a test case.  
[pdf_crash_problem.tar.gz](https://github.com/mapserver/mapserver/files/230197/pdf_crash_problem.tar.gz)

Run shp2img as show below from the `pdf_crash_problem` directory and the `test.pdf` will be created correctly even with the crash.

Here is the output from shp2img:

```
gisusr@CS24-SC-workstation:~/projects/pdf_crash_problem$ shp2img -m mapfile/test.map -o ../test.pdf
shp2img: /build/buildd/cairo-1.13.0~20140204/src/cairo-ft-font.c:450: _cairo_ft_unscaled_font_fini: Assertion `unscaled->face == ((void *)0)' failed.
Aborted (core dumped)
```

**Comment by tbonfort** [comment] 2016-04-21 15:38
Worth,
Using cairo 1.14.6 here. I am unable to reproduce your issue. Please upgrade your cairo version and report back.

**Comment by jmckenna** [comment] 2016-04-21 15:46
no issues here either with MS4W 3.1.3 (Cairo 1.14.6) on Windows.

**Comment by worthlutz** [comment] 2016-04-21 16:35
Thomas,

I don't know how to upgrade here.  My customers servers are all running 
Ubuntu 14.04 LTS (trusty) or 12.04 (precise).

Google took me here:

    https://launchpad.net/ubuntu/+source/cairo

which seems to have the same versions as on the servers.  I do not see 
any packages anywhere else.

Am I missing something or do I need to build from source to upgrade?

*Worth Lutz*

**Comment by tbonfort** [comment] 2016-04-21 16:43
Worth,
This is kind of out of scope, this very much seems to be an issue with cairo on which we have no say. You can either compile a recent version of cairo and recompile your mapserver against your local cairo copy, or get the ubuntu cairo maintainers to backport the relevant cairo fix into their own package.

**Comment by worthlutz** [comment] 2016-04-21 17:01
Thomas,

I reported this as I thought this might have been a mapserver cleanup 
problem.

My PDF files are being created so I can continue working as usual. From 
your tests, this problem will go away when we upgrade to the newest 
Ubuntu.  I'm looking into that now.

Thanks for looking into this,
*Worth Lutz*

**Closed** 2016-04-25 08:11 UTC
Labels: MapServer C Library, Output-PDF, Renderer API
