### ISSUE TITLE
Mapserver dont export correctly the spatialite format with OGR

### ISSUE THREAD

**Issue by aperi2007** [mapserver/mapserver#4856] opened 2014-01-30 13:57 UTC
Try-ing to set the mapserver trunk to export a dataset as a spatialite I found a bug.

I have installed both gdal. 1.10 compiled for use spatialite and spatialite 4.1.1.

I start from the settings for export shapefile zip like this:

  OUTPUTFORMAT
    NAME "SHAPEZIP"
    DRIVER "OGR/ESRI Shapefile"
    MIMETYPE "application/zip"
    FORMATOPTION "STORAGE=memory"
    FORMATOPTION "FORM=zip"
    FORMATOPTION "FILENAME=result.zip"
  END

This work as a charm, and the output is a zip file with inside the three files dbf,shp and shx.

After, I try the same using spatialite, with this setting:

  OUTPUTFORMAT
    NAME "SPATIALITEZIP"
    DRIVER "OGR/SQLite"
    MIMETYPE "application/spatialite"
    FORMATOPTION "STORAGE=memory"
    FORMATOPTION "FORM=zip"
    FORMATOPTION "FILENAME=result.zip"
    FORMATOPTION "DSCO:SPATIALITE=YES"
  END

Now the output is a file named result.zip , but when run the request to export , inside the file result.zip there another file named still result.zip.
This second file result.zip is not really a zip file, but instead a spatialite db wrong named.

infact If I rename it as

"result.sqlite" I can open it as a usually spatialite db.

**Comment by tomkralidis** [comment] 2015-01-28 13:02
I'm having a similar issue in a different context:

```
 OUTPUTFORMAT
  NAME "ExtendedCSV"
  DRIVER "OGR/GML"
  MIMETYPE "text/xml; subtype=ExtendedCSV"
  FORMATOPTION "DSCO:FORMAT=GML3.2"
  FORMATOPTION "DSCO:XSISCHEMA=OFF"
  FORMATOPTION "DSCO:PREFIX=woudc"
  FORMATOPTION "DSCO:TARGET_NAMESPACE=http://woudc.org/woudc"
  ##FORMATOPTION "FORM=zip"  ## default anyway
  FORMATOPTION "STORAGE=memory"
  FORMATOPTION "FILENAME=result.zip"
 END
```
The result is a prompt to download `result.zip` with a `result.zip` inside which is really an XML document.

**Comment by rouault** [comment] 2015-01-28 13:11
Looking quickly I think this is a duplicate of #4933 that is fixed in master

**Comment by tomkralidis** [comment] 2015-01-28 13:48
Workaround (in Python MapScript):

```python
    mapscript.msIO_installStdoutToBuffer()
    mapfile.OWSDispatch(request)

    content_type = mapscript.msIO_stripStdoutBufferContentType()
    content = mapscript.msIO_getStdoutBufferBytes()

    print 'Content-type: application/zip'
    print 'Content-Disposition: attachment; filename="results.zip"'
    print
    print content
```

**Comment by jratike80** [comment] 2015-11-02 11:34
Test with Mapserver 7.0 with outputformat:

OUTPUTFORMAT
NAME "SPATIALITEZIP"
DRIVER "OGR/SQLite"
MIMETYPE "application/spatialite"
FORMATOPTION "STORAGE=memory"
FORMATOPTION "FORM=zip"
FORMATOPTION "FILENAME=result.db"
FORMATOPTION "DSCO:SPATIALITE=YES"
END

WFS request with &outputformat=application/spatialite sends out file named result.db.zip, which contains file result.db which is a valid Spatialite db.

**Closed by jratike80** 2015-11-02 11:34 UTC
