### ISSUE TITLE
WFS GetFeature with OGR and SQLServer data access broken 

### ISSUE THREAD

**Issue by amaul** [mapserver/mapserver#4640] opened 2013-04-26 12:13 UTC
Since mapserver 6.2.0 beta3, the data access with OGR to a SQLServer database seems to be broken for a WFS GetFeature request. I use the mapserver binaries from the ms4w bundle  (ms4w_3.0.6 together with mapserver_ms4w-6.2.0-beta2,3,4.zip and recently ms4w_3.1.0-beta1) on a windows box with IIS. The point data are stored in the SQLServer database as geometry data type (field Shape). The same is the case for polygon data.

Here is a snippet from my map file:
...
LAYER
  NAME 'Abbaustellen'
  connectiontype ogr
  connection "MSSQL:server=****;uid=****;pwd=****;database=gm;Integrated Security=false"
  DATA "select OBJECTID,NAME as Name,STOFF as Stoff,Shape  from BSK1000_Abbaustellen___point"
  dump true
                               
  PROJECTION
    "init=epsg:4326"
  END

  METADATA 
    "ows_title" "Abbaustellen"
    "ows_extent" "5.9418 47.1265 15.3023 55.1802"
    "ows_srs" "EPSG:4326 EPSG:31465 EPSG:31466 EPSG:31467 EPSG:31468 EPSG:31469 EPSG:4258 EPSG:25831 EPSG:25832 EPSG:25833 EPSG:25834 EPSG:3034 EPSG:3035"
    "gml_include_items" "Name,Stoff"
    "gml_featureid" "OBJECTID"
  END
                               
  TYPE point
... 

I get correct results for WFS Getcapabilities and DescribeFeatureType for example by the requests

http://localhost/cgi-bin/ms-6.2.1/mapserv.exe?map=c:/inetpub/wwwroot/BSK1000/bsk1000.map&REQUEST=GetCapabilities&VERSION=1.1.0&SERVICE=WFS

and

http://localhost/cgi-bin/ms-6.2.1/mapserv.exe?map=c:/inetpub/wwwroot/BSK1000/bsk1000.map&REQUEST=DescribeFeatureType&VERSION=1.1.0&SERVICE=WFS&TYPENAME=Abbaustellen

Result is:

&lt;schema targetNamespace="http://mapserver.gis.umn.edu/mapserver" elementFormDefault="qualified" version="0.1"&gt;
&lt;import namespace="http://www.opengis.net/gml" schemaLocation="http://schemas.opengis.net/gml/3.1.1/base/gml.xsd"/&gt;
&lt;element name="Abbaustellen" type="ms:AbbaustellenType" substitutionGroup="gml:_Feature"/&gt;
&lt;complexType name="AbbaustellenType"&gt;
&lt;complexContent&gt;
&lt;extension base="gml:AbstractFeatureType"&gt;
&lt;sequence><element name="msGeometry" type="gml:GeometryPropertyType" minOccurs="0" maxOccurs="1"/&gt;
&lt;element name="Name" type="string"/&gt;
&lt;element name="Stoff" type="string"/&gt;
&lt;/sequence&gt;
&lt;/extension&gt;
&lt;/complexContent&gt;
&lt;/complexType&gt;
&lt;/schema&gt;

but a GetFeature request (which worked with the same database until mapserver 6.2.0 Beta2) like

http://localhost/cgi-bin/ms-6.2.1/mapserv.exe?map=c:/inetpub/wwwroot/BSK1000/bsk1000.map&REQUEST=GetFeature&VERSION=1.1.0&SERVICE=WFS&TYPENAME=Abbaustellen

gives the following result:

&lt;ows:ExceptionReport version="1.1.0" language="en-US" xsi:schemaLocation="http://www.opengis.net/ows http://schemas.opengis.net/ows/1.0.0/owsExceptionReport.xsd"&gt;
&lt;ows:Exception exceptionCode="mapserv" locator="NoApplicableCode"&gt;
&lt;ows:ExceptionText>msWFSGetFeature(): WFS server error. ms_error->code not found
msOGRFileNextShape(): OGR error. GetNextRawFeature(): Corrupt data</ows:ExceptionText&gt;
&lt;/ows:Exception&gt;
&lt;/ows:ExceptionReport&gt;

**Comment by szekerest** [comment] 2015-01-31 22:36
I cannot reproduce this one using the provided test data, closing

**Closed by szekerest** 2015-01-31 22:36 UTC
