### ISSUE TITLE
GAP don't work correctly

### ISSUE THREAD

**Issue by rezakho** [mapserver/mapserver#4775] opened 2013-10-02 12:19 UTC
![2](https://f.cloud.github.com/assets/2313035/1253092/de1ecee0-2b5c-11e3-99ed-82dd3bc743ee.png)

**Comment by jratike80** [comment] 2015-11-09 22:17
Closing as "Not a bug" but @rezakho did not get an answer. Mapserver-users mailing list in better forum for questions, try there if you still have the problem after two years.

**Closed by jratike80** 2015-11-09 22:17 UTC
