### ISSUE TITLE
WMS: The GEOMTRANSFORM-subroutine didn't like empty labels

### ISSUE THREAD

**Issue by JaegerFrank** [mapserver/mapserver#5225] opened 2016-01-19 14:16 UTC
WMS GetMap-Request under Apache CGI. Text-Layer from PostGIS.
Mapfile:
 ```LAYER
  ...
	TYPE point
	POSTLABELCACHE false
	CONNECTIONTYPE postgis
 ...
	LABELITEM 'txt'
	CLASS
		NAME ..
		EXPRESSION ..
		LABEL
			ANGLE [rotation]
			TYPE TRUETYPE
			FONT ..
			COLOR 0 0 0
			SIZE 12 MINSIZE 6 MAXSIZE 18
			POSITION ur
			PARTIALS false
			FORCE true
			STYLE
				GEOMTRANSFORM 'labelpoly'
				COLOR 250 250 250 
			END
		END
	END
```
When a "txt"-Column (LABELITEM) is empty (IS NULL) then Mapserver 7.0.0 loops, eating all CPU, until Apache gets a TimeOut. The same Mapfile works with Mapserver 6.4.2.
When "WHERE NOT txt IS NULL" is added to SQL in DATA the error didn't occur.
When STYLE/GEOMTRANSFORM is deleted from the mapfile, then the error didn't occur.

So I think: The GEOMTRANSFORM-Subroutine didn't like empty Labels.

**Comment by tbonfort** [comment] 2016-01-19 14:21
probably a dupe of #5167. Please reopen if not.

**Closed by tbonfort** 2016-01-19 14:21 UTC
