### ISSUE TITLE
Build fail with gcc14

### ISSUE THREAD

**Issue by Pro-pra** [MapServer/MapServer#7139] opened 2024-08-22 00:47 UTC
i check 8.0.2 and 8.2.1 version
```
mapagg.cpp:312:25: error: invalid conversion from 'unsigned char*' to 'char*' [-fpermissive]
  312 |     tags = outline.tags + first;
      |            ~~~~~~~~~~~~~^~~~~~~
      |                         |
      |                         unsigned char*
```

**Comment by rouault** [comment] 2024-08-25 13:09
This is a duplicate of #7142

**Closed by rouault** 2024-08-25 13:09 UTC
