### ISSUE TITLE
WFS returns incomplete geometry when inner ring touches outer ring 

### ISSUE THREAD

**Issue by priskahaller** [mapserver/mapserver#5299] opened 2016-06-30 15:10 UTC
Inner ring is missing in WFS GetFeature result, when geometries of inner and outer ring touch.

WKT-Geometry in PostGIS with inner ring:
```
MULTIPOLYGON(((676881.746 253159.65,676952.5 253142.812,676984.539
 253076.568,676992.16 253047.552,676907.575 252978.182,676793.971
 252977.057,676763.746 253101.446,676881.746 253159.65),(676881.746
 253159.65,676835.762 253108.566,676841.704 253079.649,676870.271
 253078.765,676924.143 253120.438,676881.746 253159.65)))
```

WFS GetFeature request returns outer ring only:
```xml
<ms:geometry>
  <gml:MultiPolygon srsName="EPSG:21781">
    <gml:polygonMember>
      <gml:Polygon>
        <gml:outerBoundaryIs>
          <gml:LinearRing>
            <gml:coordinates>
              676881.746000,253159.650000 676952.500000,253142.812000 676984.539000,253076.568000 676992.160000,253047.552000 676907.575000,252978.182000 676793.971000,252977.057000 676763.746000,253101.446000 676881.746000,253159.650000 
            </gml:coordinates>
          </gml:LinearRing>
        </gml:outerBoundaryIs>
      </gml:Polygon>
    </gml:polygonMember>
  </gml:MultiPolygon>
</ms:geometry>
```

Mapserver Version: 6.4.2
PostGIS Version: 2.2.2 r14797

**Comment by priskahaller** [comment] 2016-07-07 12:18
Has anyone encountered this problem and know how to fix it?

**Comment by aperi2007** [comment] 2016-07-07 12:47
Perhaps a geometry from an  shapefile created using arcgis ?
There is an incompatibilità between the arcgis shapefile and the ogc
software.
When the hole touch the outer ring.

I suspect the issue is with the arcgis shapefile.

Andrea.
Il 07 lug 2016 14:18, "priskahaller" <notifications@github.com> ha scritto:

**Comment by rouault** [comment] 2016-07-07 13:02
Found in http://toblerity.org/shapely/manual.html, an inner ring touching the outer ring at at most one point is OK, and ST_IsValid() on this geometry confirms it.  So I guess that the msGetInnerList() function used to distinguish inner from outer rings should be improved to deal with that use case. Currently it must work only for inner rings that are strictly inside the outer ring

**Comment by aperi2007** [comment] 2016-07-07 15:04
It is ok, but is definited differently is the shapefile come from an esri product or from a OGC product.

Infact for esri this kind of situation is resolved like a self-intersecting external ring.
Meanwhile in a shapefile from an OGC product (like qgis) it is resolved like an hoe touching the external ring.

Something is explained in this command of postgis (see the "esri flag").

http://postgis.net/docs/manual-2.2/ST_IsValidDetail.html

>Consider self-intersecting rings forming holes as valid. This is also know as "the ESRI flag". Note that this is against the OGC model.

**Comment by priskahaller** [comment] 2016-07-08 09:14
Thank you for your answers.
In this particular case there's no esri software involved, the geometry was imported to PostGIS by FME from Oracle Spatial and it is valid either way (ST_IsValidDetail() returns (t,,) with or wihout esri flag).
Oracle geom.get_wkt() returns a compoundcurve: 
CURVEPOLYGON (COMPOUNDCURVE ((676992.16 253047.552, 676984.539 253076.568, 676952.5 253142.812, 676881.746 253159.65, 676924.143 253120.438, 676870.271 253078.765, 676841.704 253079.649, 676835.762 253108.566, 676881.746 253159.65, 676763.746 253101.446, 676793.971 252977.057, 676907.575 252978.182, 676992.16 253047.552)))

**Comment by priskahaller** [comment] 2016-08-29 07:58
Has anyone an idea how to fix it?

**Comment by aperi2007** [comment] 2016-08-29 09:59
Have you tried an

Update table set geometry=st_makevalid(geometry) where
st_isvalid(geometry)=false;

?

Il 29 ago 2016 9:58 AM, "priskahaller" <notifications@github.com> ha
scritto:

**Comment by nischmi1** [comment] 2016-08-29 10:13
It seems (from looking at msGetInnerList()) that everything that is not an outer ring will be an inner ring. There is no test procedure for inner rings. But the test procedure for outer rings msIsOuterRing() is probably not suitable to distinguish the special case which causes problems here.
I am pretty conviced that the problem lies in the code and not in the data, as @aperi2007 suggests... while I think I can see the problem, I have no idea as to what the solution would be.

**Comment by priskahaller** [comment] 2016-08-29 11:14
@aperi2007:  All geometries are valid

**Comment by rouault** [comment] 2016-09-08 10:05
Fixed in branch-7-0 and in master

**Closed by rouault** 2016-09-08 10:05 UTC

**Comment by priskahaller** [comment] 2016-09-08 10:57
Great, thank you!

**Comment by priskahaller** [comment] 2016-09-19 08:32
@rouault:  When is the next mapserver package release (that incudes this bug fix)  planned?

**Comment by rouault** [comment] 2016-09-19 10:18
Soon hopefully : https://lists.osgeo.org/pipermail/mapserver-dev/2016-September/014920.html
